### ISSUE TITLE
SFX lookup not quite live? or is coverage simplified?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1003]
https://www.library.ualberta.ca/catalog/1000000000274727

I just edited the threshold to read "Available in 1997 volume: 35 issue: 1
Available from 1997 volume: 35 issue:3 until 1998 volume: 36 issue:2" (i.e. v.35,iss.1; v.35,iss.3 to v.36,iss.2, [as seen in the Get It window](http://resolver.library.ualberta.ca/resolver?url_ver=Z39.88-2004&url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&rfr_id=info:sid/sfxit.com:kbmanager&sfx.ignore_date_threshold=1&rft.object_id=1000000000274727)), but I am not seeing the change in the Blacklight record. 

I'm wondering now if it's because the coverage statement has been simplified for display in Blacklight (showing just the earliest and latest volume/date for a given target, without the gaps)...?

**Comment by redlibrarian** [comment]
The lookup is live, and I'm not doing any processing on the data. I think it's more likely that the SFX API isn't handling the multiple thresholds properly. I'll look into it.

**Comment by redlibrarian** [comment]
Huh. Turns out I was wrong about *everything* in the holdings table being a live lookup. The XML response from the API (http://resolver.library.ualberta.ca/resolver?url_ver=Z39.88-2004&url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&rfr_id=info:sid/sfxit.com:kbmanager&sfx.ignore_date_threshold=1&rft.object_id=1000000000274727&sfx.response_type=simplexml) does not contain subscription information - that has to be drawn from the SFX data file that's processed once a night. So, target name/presence, note, and OUR info is all live, but the coverage column will take a day to update.

**Comment by theLinkResolver** [comment]
@ualbertalib/serials-cataloguing See thread for a note re. currency of SFX coverage in Blacklight.
