### ISSUE TITLE
Change wording to barcode & PIN login on place holds screen

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#1014]
Can the text be a bit larger and simply be a link that says Login with Barcode and PIN

If we want it to be more specific it could say: Login with Barcode and PIN (NEOS, TAL, Academic Visitors, Members of the Public)

**Comment by linds37** [comment]
correction: Login with Barcode and PIN (Alumni, Visitors, NEOS, TAL, Members of the Public)

I used the brackets to mirror the heading for My Account, which says "My Account (for current students, staff and faculty)", but it could try to address the group concerned:

Alumni, Visitors, NEOS, TAL, Members of the Public: Login with Barcode and PIN

**Comment by redlibrarian** [comment]
@linds37 I've changed the wording/size to this:

![image](https://cloud.githubusercontent.com/assets/1093066/16959369/fdb1ca7c-4da1-11e6-8072-6cc98db9c099.png)


I'm reluctant to add the user types as we don't have a lot of room in that box, and it risks overwhelming the place hold button. What do you think?

**Comment by linds37** [comment]
Can you think of a good way to differentiate between the two? I think it's confusing not to.  Maybe it doesn't need to say "with barcode and PIN". What if it said "NEOS, TAL, Alumni, Public: Place Hold here"

**Comment by linds37** [comment]
... and not bold it, so as not to detract from the button for UA users?

**Comment by linds37** [comment]
"NEOS, TAL, Alumni, Visitors: Place Hold here" -- that's better

**Comment by redlibrarian** [comment]
Quite honestly, I think it's too much text, and looks really clunky both in relation to the place hold button and the list of other options. @ualbertalib/discovery-testing What does anyone else think?

![image](https://cloud.githubusercontent.com/assets/1093066/16963014/83f216dc-4db1-11e6-82cd-2d3046582e4d.png)

**Comment by linds37** [comment]
If Blacklight can detect single sign-on, can it suppress the barcode & PIN link?

**Comment by redlibrarian** [comment]
Blacklight currently doesn't look at a user's authentication at all (that's handled by the place hold page, outside of Blacklight). If it's possible, it would be a large enough piece of work that it would have to be its own project, and we'd have to decide on the priority (i.e. what doesn't get done because we're doing that). It would also mean that for any U of A student or faculty who hasn't signed in yet, they would see the barcode and pin link (i.e. they would see it sometimes and not others).

**Comment by linds37** [comment]
I've had a suggestion for wording: Not U of A student/staff? Place hold here.

**Comment by seanluyk** [comment]
How about "External Users: Click Here"?

**Comment by redlibrarian** [comment]
Currently in production the label is "Place Hold with Barcode and PIN" in bold text. I don't want to get into wordsmithing this too much (as we've found in the past). IMO avoiding listing constituencies is preferable so that we don't have to constantly keep that list updated, and I'm not sure "External User" is understood by anyone but staff. I propose we leave it as is for now and revisit at the end of term. Does that sound OK?

![image](https://cloud.githubusercontent.com/assets/1093066/17634251/f4618692-608e-11e6-9a2d-9ccebf880e20.png)

**Comment by seanluyk** [comment]
Agreed, this is maybe another case where we could ask users what they think it should say, but otherwise what's there is fairly neutral

**Comment by redlibrarian** [comment]
OK, sounds good. One thing on my list is to do some more user testing towards the end of term.
