### ISSUE TITLE
Call numbers in Bookmarks view

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#1016]
This comment/suggestion came in from a staff member:
"I tried collecting a list of bookmarks for a patron. When I clicked on 'Go to Bookmarks', I did get a list, but the call numbers are not visible, which makes the list rather moot for printing and offering up to the patron to go find the items on the shelf. I also tested the email feature, and the call numbers don't appear there either; it just provides links to the original catalogue records. 
Having the call numbers appear somewhere immediately in the list would be extremely helpful, since printing that list directly at the service desk saves LOADS of extra time and duplicated effort both for staff as they provide 'point of need' reference, and for patrons who have usually done some searching already before they come to us at the desk."

**Comment by theLinkResolver** [comment]
This is such a desirable feature... I'm just not sure how to execute it --

Which call number do we choose to present in the bookmark list for these titles?
https://www.library.ualberta.ca/catalog/2378310
https://www.library.ualberta.ca/catalog/2318161
https://www.library.ualberta.ca/catalog/1295581

Maybe the solution is to include all call numbers, somehow, but what if someone decides to bookmark one of these?:
https://www.library.ualberta.ca/catalog/4164765
https://www.library.ualberta.ca/catalog/2654050

**Comment by redlibrarian** [comment]
As Scott points out, the fact that we have different call numbers for
different items makes this tricky. I removed the call number from the email
functionality, because - while we can include all call numbers in an email
- we can't include them all in a text, and it made sense for email and text
functionality to be the same.

One suggestion from a SLAC member was that there could be an email/text
link next to each *item* rather than at the bib record level. I like this
idea, though it will require some thinking about how to design the page
properly.

I appreciate the staff member's use-case, so this merits some discussion,
I'm just not sure how we can usefully make this happen.


On Wed, Jul 13, 2016 at 3:00 PM, Scott Davies <notifications@github.com>
wrote:

> This is such a desirable feature... I'm just not sure how to execute it --
>
> Which call number do we choose to present in the bookmark list for these
> titles?
> https://www.library.ualberta.ca/catalog/2378310
> https://www.library.ualberta.ca/catalog/2318161
> https://www.library.ualberta.ca/catalog/1295581
>
> Maybe the solution is to include all call numbers, somehow, but what if
> someone decides to bookmark one of these?:
> https://www.library.ualberta.ca/catalog/4164765
> https://www.library.ualberta.ca/catalog/2654050
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/1016#issuecomment-232485147>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCtyjB74_l4jK0QXsXjCUoAnsCKGtd_ks5qVVHtgaJpZM4JL08M>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by redlibrarian** [comment]
I've managed to get the email/text each item (including call number) working, so it may be that we can figure out how to deal with call number/locations in bookmarks view. I think the design of this in a consortial environment will take some discussion/planning.
