### ISSUE TITLE
Does Blacklight search the 050 MARC field in Symphony? Creating a print/virtual shelflist

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#1017]
David was telling me that a lot of ebook records have a call number in the 050 field. Is it possible for Blacklight to include 050 in keyword searches?

If yes, does that mean we could create a "shelflist" that includes both print & e resources in a call number range?

The call numbers for UA books in Symphony have a space between the first letter and the number. The ebook call numbers in the 050 field have no space (like MacEwan call numbers). Ie: P 118.2 as opposed to P118.2. Is this something that could be overcome?

**Comment by theLinkResolver** [comment]
It looks like we are just indexing the 090 (local call number) now. The 050 is used for the call number faceting. In that sense, it is available for the purpose described, but only at the very highest level of classification (i.e. the first digit of the class number only, e.g. H (Social Sciences) but not HF (finance), and certainly not to the level of the numeric ranges within a subclass), so actually not very useful for this.

I think that if the 050 was keyword-searchable, one could construct a search that produces a "shelflist" that drills down to a specific range within a subclass, e.g. HF5428-5429.6 (retail trade). However, to properly construct the search, you would need to know all the possible numbers in a range like that, because we can't do truncation, and also the search doesn't work if I omit decimals. 

![retail trade](https://cloud.githubusercontent.com/assets/14913579/16848735/723eaa64-49b4-11e6-928e-8c735a25e7db.png)

For "retail trade", your search string would be _HF5428 OR HF5429 OR HF5429.12 OR HF5429.15 OR HF5429.2 OR HF5429.215 OR HF5429.22 OR HF5429.225 OR HF5429.23 OR HF5429.235 OR HF5429.25 OR HF5429.255 OR HF5429.26 OR HF5429.265 OR HF5429.27 OR HF5429.275 OR HF5429.28 OR HF5429.29 OR HF5429.3 OR HF5429.4 OR HF5429.5 OR HF5429.6_

And yes, [it works](https://www.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=HF5428+OR+HF5429+OR+HF5429.12+OR+HF5429.15+OR+HF5429.2+OR+HF5429.215+OR+HF5429.22+OR+HF5429.225+OR+HF5429.23+OR+HF5429.235+OR+HF5429.25+OR+HF5429.255+OR+HF5429.26+OR+HF5429.265+OR+HF5429.27+OR+HF5429.275+OR+HF5429.28+OR+HF5429.29+OR+HF5429.3+OR+HF5429.4+OR+HF5429.5+OR+HF5429.6&title=&author=&subject=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search&utf8=%E2%9C%93&search_field=dummy_range&range[pub_date][begin]=&range[pub_date][end]=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced)!

The reason it works is because MacEwan formats their call numbers this way, and therefore, there is some data in the 090 field on which to search, and the results look good to me. As I say, if the 050 was also searched, this would cover anything with an 050 (lots of e-books and hopefully most other stuff). The difference in formatting, as you point out, could not be easily overcome, but in theory, one of our records with an 090 like HF 1023 would likely have an 050 formatted as HF1023. Also, I guess you could add a bunch more OR statements to cover your bases (e.g. HF1023 OR "HF 1023").

Sorry for the novel, but I want to show how this _is_ possible, rather than just say "it's complicated"! :)

And I'm not officially volunteering, and I don't speak for everyone up here, but I would like to think that Bib Services cataloguers would be more than happy to provide assistance with this, if a liaison or other public service staff member wanted to work out a search string.

**Comment by linds37** [comment]
Thanks for investigating, Scott. I think it would be great to look into this further, and to consider making the 050 field searchable so that ebooks could come up for call number keyword searches

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
