### ISSUE TITLE
Item not findable in BL by keyword search of terms in contents note

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1059]
This isn't a bug, as the item is findable due to the additional Italian 245. The issue here is with the 500 field not being indexed for search, while it *is* indexed for display. I've added this field to #1146 .

**Comment by theLinkResolver** [comment]
I thought we were indexing general notes but I checked and we are not. That needs some thought, discussion and/or monitoring.

With that said, I would have expected a uniform title entry in this record for the Italian and it's not there. It's missing from the master record in OCLC, which explains it, somewhat. I have put it in. Whenever this change gets indexed (?), a search should return this book. And it will now come up in a title search in the classic catalogue, thanks to my correction (rather than just a general/keyword search).

**Comment by seanluyk** [comment]
Thanks @theLinkResolver for the uniform title. The item is now findable in BL. I think that we really need to index general notes, for the reason you mention. Uniform title aren't always added, so we can't rely on them.

**Comment by seanluyk** [comment]
This particular item is findable so I suspect general notes are now being indexed. Will verify in Bib Services meeting what needs to be done.

**Comment by seanluyk** [comment]
Fixed
