### ISSUE TITLE
database record displaying description of different database record

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1063]
Referred from [Helpdesk ticket](https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=35787).

A search for "Comprehensive Composite Materials" in Blacklight Databases is returning [this record](https://www.library.ualberta.ca/catalog/11710418), which has the right title but the description for Compendex.

A search for Compendex links to [this record](https://www.library.ualberta.ca/catalog/11710417) (the correct database record).

Searches for these titles in the database list look OK:
- [Comprehensive Composite Materials](https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=1414)
- [Compendex](https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=180)

@redlibrarian Can you tell what is going on here?

**Comment by redlibrarian** [comment]
@theLinkResolver I can see the Compendex description ("Ei Compendex (1884 to the present) provides international coverage of all fields of engineering including related areas of applied science, management, and energy.") in the libguide asset, so that's where that text is coming from. The more info also seems to be coming through. I know Elizabeth says the asset looks fine in libguides, but that's where I can see the Compendex description...

**Comment by theLinkResolver** [comment]
@redlibrarian Thanks, will followup with her.

**Comment by theLinkResolver** [comment]
non-Blacklight problem - closing
