### ISSUE TITLE
Verify and correct place hold display place hold logic

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1076]
Out of curiosity, I tried placing a hold on this record in test https://search-test.library.ualberta.ca/catalog/6601213 and it let me. Reserve items should not be hold-able.

**Comment by redlibrarian** [comment]
It looks like SirsiDynix may have changed the Sirsi Web Services XML response, which has broken the "holdable/non-holdable" logic. I'll have to figure out how they're doing it now.

**Comment by redlibrarian** [comment]
This item is holdable in iLink, due to one of the items being holdable. http://www.library.ualberta.ca/permalink/opac/6601213/WUAARCHIVE

When you try to place a hold in Blacklight, however, it gives you a "this item cannot be checked out" message.

**Comment by redlibrarian** [comment]
@linds37 @theLinkResolver (for reference, this is the issue I've been discussing in the email thread).

**Comment by theLinkResolver** [comment]
I'm going to log my findings here for future reference with thanks to Peggy.

Here is how the circ rules are checked:

- The Place Hold button is presented (in iLink and Blacklight) when there is a holdable location for any of the items in the record. "Checked out" is a holdable location, so the hold button is available.

- After the user enters their barcode (if nec) and pickup location, and clicks the button, then the item type is checked, as to whether it is a holdable item type or not.

So for this record, currently, the place hold button is available because the AGL copy is signed out. When the user clicks place hold, that is the copy that is selected for the hold (the others are excluded at that point). Then when the user completes the hold, the item type is checked, which is No Loan, and the hold is not allowed.

Here's what must have happened with Lindsay's hold. One or more of the reserve copies must have been signed out at the time the hold was placed. Therefore, the AGL item and the checked out Reserve copy(ies) were considered for the hold. The AGL copy failed the item type test, but the reserve copy accepted the hold, because the item type for reserve material is BOOK, which is a holdable item type.

This is a known problem, and holds on reserves have been regularly cancelled (I think by Access Services). However, with the textbook initiative, holds on reserves (due to the logic described above) have exponentially increased, and testing is being done to develop an item type that can be applied to reserves in order to block holds when those reserve items are checked out.

**Comment by seanluyk** [comment]
Was able to successfully place hold on this item (1 copy is holdable), so logic must be working. Closing.
