### ISSUE TITLE
unwanted info displaying in ejournal holdings table

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1077]
span class='nofulltext'This item is not in the catalogue./span
Coverage information temporarily unavailable. 

e.g. https://www.library.ualberta.ca/catalog/954927657963

I've seen it elsewhere but not consistently.

**Comment by redlibrarian** [comment]
Interesting. I've never seen that before - I'll look into it.

**Comment by theLinkResolver** [comment]
Another
https://www.library.ualberta.ca/catalog/110978984080311

**Comment by redlibrarian** [comment]
The SFX service within Blacklight has always been set to ignore LOCAL_CATALOGUE_SIRSI_UNICORN and MESSAGE_NO_DOCDEL_LCL targets, but for some reason it has started to try to display the information. Since we don't want these to display, they actually aren't displaying properly... I need to track down why this might have changed.

**Comment by redlibrarian** [comment]
Link to XML response: http://resolver.library.ualberta.ca/resolver?ctx_enc=info%3Aofi%2Fenc%3AUTF-8&ctx_ver=Z39.88-2004&rfr_id=info%3Asid%2Fualberta.ca%3Aopac&rft.genre=journal&rft.object_id=954927657963&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=inf%20o%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004&sfx.response_type=simplexml

**Comment by redlibrarian** [comment]
This is working in search-test now.
