### ISSUE TITLE
[Discovery] quotes in contents field being rendered as &quot;

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1085]
This must have something to do with the formatting that is applied to the contents field, as quotes look okay elsewhere in the record display.

Examples:
https://www.library.ualberta.ca/catalog/7583704
https://www.library.ualberta.ca/catalog/7583375

**Comment by theLinkResolver** [comment]
Similar to #378, though that one was specific to the articles box.

**Comment by weiweishi** [comment]
- seems to be escaped properly in Solr content_tesim
- seems the problem happens when pulling information from Solr to the application. 
- A hack in the code treats content_tesim differently than "summary" or other text fields.  https://github.com/ualbertalib/discovery/blob/master/app/views/catalog/_show_default.html.erb#L31

**Comment by seanluyk** [comment]
Working in current version in prod
