### ISSUE TITLE
articles - scholarly vs. news & magazine

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1107]
From today's ACRL Virtual Conference session "Up and Running with Bento: Implementing bento search with a new discovery service and homepage update, all in a semester", I thought that [UNC Wilmington's separation of scholarly articles vs. news & magazine articles](http://library.uncw.edu/search_randall/shakespeare) was an interesting idea. (Those in public service would have a better grasp on the usefulness of this for our users... and of course, the users themselves may tell us in a testing/feedback scenario.)

**Comment by redlibrarian** [comment]
I've heard suggestions like this from public service before, so it might be worth checking into. My concern would be that the metadata wouldn't be good/clean enough to do it right - we already know how difficult it is to precisely define a particular content type at the level we're doing it now. In order to split up articles in this way, the publisher-supplied metadata in EDS would have to be present/correct (a stretch) and it would have to be consistent across all the different publishers (another stretch). It would be interesting to find out what staff/student feedback at Wilmington has been.
