### ISSUE TITLE
Google custom search?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1108]
Another from today's ACRL Virtual Conference session "Up and Running with Bento: Implementing bento search with a new discovery service and homepage update, all in a semester". UNC Wilmington uses Google custom searches to deliver results from their library website and other sites. @redlibrarian Would this be an alternative to adding LibGuides to the Solr index as a 'collection'? I guess there would be some tradeoffs. (Also I was wondering about something like the William C. Wonders Map Collection Database, but that does not appear to be indexed by Google.)

**Comment by redlibrarian** [comment]
To me, this comes back to the old debate: if we know people are already searching Google, why pull Google search content into our discovery layer.

The big issue here is the lack of unified index. If we have some content in the Solr index and some content coming in via API (from Google or anywhere else), then we end up with the same problem we have with EDS: users can't use a single search to search and then refine results. Since we have a Solr index for our content, it makes sense to use it as much as possible, in order to get the benefits of all content indexed together. We're stuck with articles, unfortunately, but for other content, I think it makes sense to index it all together.

**Comment by theLinkResolver** [comment]
Whatever the method, I've always wondered what LibGuides results would actually look like. I guess the page or tab title and a snippet showing the relevant text? It would nice to find out if users would appreciate seeing results _about_ resources alongside the resources themselves, or if that would be noise in a search context.

**Comment by redlibrarian** [comment]
We have talked about doing something like that, similar to Google's knowledge card and EDS' research starters. In that sense, a search for a particular topic could provide a link to the subject libguide alongside the search results - we wouldn't need to search Google for that, we could do an API search against LibGuides directly. However, we *also* think of libguides as resources in and of themselves, which means we would want to index them alongside other content, IMO.

**Comment by seanluyk** [comment]
Interesting...perhaps this kind of functionality will come up in our proposed staff survey.

**Comment by seanluyk** [comment]
Out of scope for current Discovery project, closing.
