### ISSUE TITLE
Subject terms not working

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1109]
I am having trouble locating items on the Michif language in the discovery system.

Here is a known item I already have:

https://www.library.ualberta.ca/catalog/7120087

when I click through to see if there are more like it, using the link at the bottom in the Subjects:
 
Michif language  > Juvenile sound recordings
I am just getting a random list of Juvenile sound recordings, rather than ones that are in Michif.  

129 items and all various languages.  

The subjects search in the record are not working correctly.

**Comment by seanluyk** [comment]
Re: the subject chaining issue. v3.0.82. It may not actually be fixed in test after all. If you click on [Michif language > Juvenile sound recordings](https://search-test.library.ualberta.ca/catalog?q=Michif+language+%2B+Juvenile+sound+recordings&search_field=subject&view=brief) it's acting as a keyword search within the subject field (the second result is teach me Italian). If I add [quotes to the URL](https://search-test.library.ualberta.ca/catalog?q=%22Michif+language%22+%2B+%22Juvenile+sound+recordings%22&search_field=subject&view=brief) I believe it's in line with expectations for how subject searches work. We should talk about this in person though before making any changes as this has some usability implications

**Comment by seanluyk** [comment]
Here's an example of a URL constructed to do an exact match: https://searchworks.stanford.edu/catalog?q=%22English+language+Dictionaries+Japanese.%22&search_field=subject_terms

**Comment by seanluyk** [comment]
Closing is this is being solved in the next release/this information is duplicated elsewhere
