### ISSUE TITLE
Incorrect holdings showing for missing UofA item in list view

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1118]
To replicate this issue:

1. Click on the first record from this [results list](https://www.library.ualberta.ca/symphony?q=%22Interpretive+Phenomenological+Analysis%22+smith+flowers+larkin)
2. Note that in list view, UofA holdings are indicated, yet no holdings are listed in record view

Workflows confirms that the item is marked missing, so UofA holdings should not be appearing in list view

**Comment by seanluyk** [comment]
Not able to replicate, so must have been fixed in a monthly re-index.

**Comment by theLinkResolver** [comment]
@seanluyk Not going to reopen this one, but I will draw your attention to [this ticket](https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=49981#247746). Note, the situation has already changed. The item had been marked missing but was located, discharged, and checked out to someone in the last hour. 

The issue is seeing a location in the results list view but not in the record view. The solution would be to add some logic to not show a location if the current location for all copies=shadowed location(s), which would be another list to maintain and maybe some additional data to process to produce the results list. Fun. Hence me not reopening the issue (although it might come up in the NEOS discovery context at some point). 

FWIW, it had previously been asserted (#663) that the record view should be considered the definitive list of holdings locations.

**Comment by seanluyk** [comment]
@theLinkResolver thanks for reporting this. The method used to display holdings in the list view is less than ideal, as it isn't a live lookup like it is in the records view, so it can never be 100% accurate for cases like shadowed locations. A redesign in a future phase would have to account for this, and I suspect would change to a live lookup
