### ISSUE TITLE
Index 505g, t, and r for additional contents info.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1123]

**Comment by theLinkResolver** [comment]
#1121

**Comment by seanluyk** [comment]
@theLinkResolver would you mind adding an example record or two to this?

**Comment by theLinkResolver** [comment]
https://search.library.ualberta.ca/catalog/8340149

https://search.library.ualberta.ca/catalog/6668014 (note, no $r in this one; also has two 505s)

https://search.library.ualberta.ca/catalog/8433459 (note, no $g in this one)

**Comment by seanluyk** [comment]
@theLinkResolver thanks for these - I'm happy to report that this is fixed in test, and should be in production shortly, with one minor consequence being that repeated 505 notes aren't appearing on separate lines, which we'll fix. For example, here is how 6668014 appears:

![capture](https://user-images.githubusercontent.com/14880206/53596097-3a245380-3b5c-11e9-82af-80acfd634d3a.PNG)
