### ISSUE TITLE
Display 245$n and 245$p as part of title.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1193]
I just implemented this for NEOS Blacklight, so I'm making the same change to discovery. Currently section_name ($p) and section_number ($p) are displayed as part of the metadata block in an item record. They should be part of the integrated title display.

**Comment by seanluyk** [comment]
Since this was [completed in NEOS Discovery](https://github.com/ualbertalib/NEOSDiscovery/issues/140), it should be easy enough to do here. The fields are already mapped, just not being appended to the title

**Comment by theLinkResolver** [comment]
I see this was done, as noted, although I would be in favour of tweaking the punctuation and THEN applying that to UA discovery.

NEOS discovery example: https://catalogue.neoslibraries.ca/catalog/431354

Current:
Historical abstracts Part A. Modern history abstracts, 1450-1914.

Tweaked:
Historical abstracts. Part A, Modern history abstracts, 1450-1914.

- period before part number
- comma instead of period between 

c.f. [Stanford](https://searchworks.stanford.edu/view/362375)

**Comment by seanluyk** [comment]
Fixed in test, closing.
