### ISSUE TITLE
Discovery: Create wireframe for the micro-format/newspaper request form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1216]
To create the wireframe in Balsamiq for the new request form based on the requirements. When the wireframe is completed, send it to Sean and CJ for review. 

**Current form**
https://web.library.ualberta.ca/catalogue/bard/

**Required field**
- Name and email address of the user who requested the object.
- Title (auto-populated into the form)
- URL to the record (auto-populated into the form)
- One of these: Year/Volume/Date (if not applicable, user has to indicate it's not applicable)
- pick up location

**Title of the form**
RCRF Depository Library Request Form (Microform/Newspapers)

**Language to use as the description on top of the form**

At the top of the form:

We need additional publication information (e.g., year, specific date, section, article title, etc.) for us to retrieve this item. Please provide as much detail as possible.

**Comment by seanluyk** [comment]
@weiweishi  - may be easier to discuss this in person, but is a new form needed or would a link to the existing form suffice?

**Comment by weiweishi** [comment]
We can probably discuss this in person. CJ’s hope is to get rid of the current form, and have a new form pre-populated with the information needed for the request. Current form won’t allow for prepopulating information. 

We do need to talk about another requirement of tracking these requests. We’d like to push it back to something that is not included in Discovery.

**Comment by theLinkResolver** [comment]
@weiweishi @seanluyk This may be obvious but I'll chime in that one requirement may be that the form is in a pop-up window, so that the user can consult the record for the volume number they required (if applicable to their request).

**Comment by weiweishi** [comment]
Sorry Sean. May I should be more clear?  Some of these requirements still
apply, but they should be more explicitly listed in this issue instead?
https://github.com/ualbertalib/discovery/issues/1184

Let's chat to clarify!


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by weiweishi** [comment]
@murny 
The language on the form was on the ticket but comparing to what is current form, is much simpler. I've also added the title for the form.

**Comment by murny** [comment]
Okay, created a simple mockup of the requirements outlined above:
https://balsamiq.cloud/s3awdua/pmnl7qx/r8F6C

Let me know if you got any feedback!

**Comment by seanluyk** [comment]
@murny just sent CJ a message for feedback. Will add what he says here. Thanks!

**Comment by seanluyk** [comment]
@murny here is CJ's feedback, let me know if you have any questions: 

- Relabel "Record URL" to "Item URL" and add an example (e.g. https://library.ualberta.ca/catalog/8081552) because CJ intends to use this form on the website as well. This field should be auto-populated when the request is placed via the catalogue if possible.
- Perhaps this field could read "Year/Volume/Date, other notes" and have a larger text box? 
- Our holds form in Discovery uses the following language:
- Pickup Library (as opposed to Pick Up Location)
- The drop down should start with "Please select a library" and the form should only be accepted if a library is selected. I'm afraid people might not change it from Augustana.
- The button that reads "Request Pick Up" could change to "Place Request"

**Comment by murny** [comment]
Sounds good. Made all the changes requests. Should now be reflected in the mockup: https://balsamiq.cloud/s3awdua/pmnl7qx/r8F6C

Note for 2nd bullet, instead of renaming field to "Year/Volume/Date, other notes", I just made it say "Additional Notes" and gave it a placeholder of "Please provide any additional information that can help us retrieve this item. e.g. Year, Volume, Specific Date, etc." Which should capture the idea of the textarea

Let me know if you got any other feedback

**Comment by seanluyk** [comment]
Thanks @murny here is CJ's latest feedback:

Looks good! 

Some notes on the drop-down menu:

- There is no Physical Sciences library, so it should be removed from the drop-down menu. 
- Perhaps we could use the same names as in Discovery for our libraries (although consistent with the hyphen between name and subject)
- Our colleagues at BSJ may appreciate seeing the accent in Bibliothèque. Would that be possible?

Thanks!

**Comment by murny** [comment]
Sure thing!

I literally just copied and pasted the list of locations from the old form: https://web.library.ualberta.ca/catalogue/bard/

So we definitely can do everything your asking for without any worries.

Will have an updated form probably tomorrow with suggested feedback

**Comment by seanluyk** [comment]
@murny that form has been around for a long time by the looks of it, it'll be nice to have all the locations up to date! Here are the locations that need to be in there with the complete names. I think this is what CJ means about the hyphens.  

University of Alberta Augustana
University of Alberta Bibliothèque Saint-Jean
University of Alberta Cameron-Science & Technology
University of Alberta HT Coutts-Education
University of Alberta JA Weir-Law
University of Alberta JW Scott-Health Sciences
University of Alberta Rutherford-Humanities & Social Science
University of Alberta St Joseph's College
University of Alberta Winspear-Business

**Comment by theLinkResolver** [comment]
I think Education wants to be known as Education and KSR now, or perhaps Education and Kinesiology, Sport, and Recreation

**Comment by seanluyk** [comment]
@theLinkResolver  - good catch, this is another name change not yet reflected in BL. I've updated the comment above

**Comment by murny** [comment]
[Wireframe mockup](https://balsamiq.cloud/s3awdua/pmnl7qx/r8F6C) now has requested changes including updated list of locations

**Comment by weiweishi** [comment]
@seanluyk I think this can be considered completed/signed-off?

**Comment by seanluyk** [comment]
@weiweishi ditto - all the wireframes have been approved
