### ISSUE TITLE
Implement RCRF No Loan Form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1260]
Once the wireframe is finalized here, #1216, the form needs to be developed on the front end:

https://balsamiq.cloud/s3awdua/pmnl7qx/r8C53

**Requirements**
Auto-populated fields:

- the title of the object
- call number of the object.

The request form should be sent to depository@ualberta.ca, and ill@ualberta.ca

Also question for the URL for this form? Could we do something like:
https://library.ualberta.ca/rcrf-noloan-form or https://library.ualberta.ca/rcrf-noloan-request ? etc?

**Comment by seanluyk** [comment]
@weiweishi my preference is /rcrf-readonsite. I know the form is labeled no loan, but we'll need to talk to CJ about this. Since the location/status is called ReadOnsite, I think it'll be confusing for users if we use the term no loan to refer to these materials

**Comment by murny** [comment]
One thing we need to think about (for all three of these request form tickets: #1260, #1259 and #1258) is how emails are sent in our different environments. Often times a bad application will send real emails to real people on UAT/Staging environments! Which is something we should avoid doing. So for the different environments here's what we need to do to prevent this:

#### Development
By default development should not be sending emails. Typically in a rails application, the email is outputted to the logs. You can bring something like `letter_opener` (https://github.com/ryanb/letter_opener) which allows the email to be nicely previewed in a new tab in the browser instead.

#### Test
Typically you don't have to worry about test environment. We should be configuring this using `ActionMailer::Base.delivery_method = :test` which makes emails not send out in test environment but instead puts the email on an array instead. More info here: https://guides.rubyonrails.org/testing.html#testing-your-mailers

#### UAT/Staging
We should write a [email interceptor](https://guides.rubyonrails.org/action_mailer_basics.html#intercepting-emails), which intercepts any email that is being send out by discovery, clears the `to` fields and sends the email to `dittest@ualberta.ca` (or something else?) instead. You can also append some comments in the body of the email explanaing why this happened (this was sent out in a non production environment) and who this email was originally for, etc.

#### Production
I assume discovery is already setup to send emails (considering we got [one mailer](https://github.com/ualbertalib/discovery/blob/master/app/mailers/corrections_mailer.rb) and [some mail configuration setup](https://github.com/ualbertalib/discovery/blob/master/config/environments/production.rb#L66-L69) already. This is great as this means we probably have a SMTP server/postfix/something setup in production from our ansible/etc that is doing the actual emailing of the emails.)
So nothing much needs to be done here....we just create a new mailer for the forms and send a real email out.

**Comment by seanluyk** [comment]
@murny one thing to be aware of regarding emails is that for some reason the mailer isn't currently working. Submitting a correction from a record is supposed to result in a helpdesk ticket, but I just tested this and it didn't work

**Comment by murny** [comment]
@seanluyk That's good to know. Maybe email isn't setup for discovery? Will need to double check with ITS team for what the status of that is

**Comment by seanluyk** [comment]
@murny weird...the email did now show up in the helpdesk, but it was delayed a little, so maybe it's working? The other place is the email me button, which also does appear to be working now

**Comment by murny** [comment]
Since I'm leaving on vacation, here's some documentation of where I am at and whats left (in case anyone needs to pick up this):

For Email Interceptor piece, take a look at this gist for how to implement:
https://gist.github.com/murny/287623f9d2d8bcbaae74d49f13b53d89
Code is pretty much complete, just didn't get a chance to finish it.

For development add this gem and change delivery_method in `development.rb`: 
https://github.com/ryanb/letter_opener#rails-setup

So we can send emails in development without worries for manual testing.

For the form itself, essentially your building a contact email form (lots of examples online).
You want to back this form via a non-activerecord model that will look something like this (official docs example: https://guides.rubyonrails.org/active_model_basics.html#model):

```ruby
# app/models/rcrf_no_loan.rb
class RcrfNoLoan
  include ActiveModel::Model

  attr_accessor(
    :title,
    :email,
    :name,
    # etc...
  )

  # validations just like a real model
  validates :title, presence: true
  validates :email, presence: true, email: true
  validates :name, presence: true
  # etc....

  def deliver
    if valid?
      # Do something interesting here
     # - send email
      # - log events, etc.
    end
  end
end
```
(Note: Rails 5 makes this much nicer with something called "ActiveRecord Attributes API" (`include ActiveModel::Attributes`), but since we are on Rails 4, we have to use the old way)

Then just need to add some routes, a controller and some views and your done (the three request forms should probably be sharing the same controller and view folder, etc)

Note: regarding the trickiness with pre-population of fields (title, etc), this can be handled in the controller (passing the request params into the `Model.new` which the form will use to render out it's content)

**Comment by seanluyk** [comment]
In production behind a feature flag. Will check with CJ again soon to confirm when we can remove it, but this is otherwise done.
