### ISSUE TITLE
BPSC and RCRF form submission completion redirection behaviour

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1443]
**Describe the bug**
When either of the forms (BPSC or RCRF) are submitted, the users are redirected to the library homepage instead of the item that they were looking at.

**To Reproduce**
Steps to reproduce the behaviour:
1. Submit a form
2. Redirected to the home page

**Expected behaviour**
When a user submits a form, the completion message appears on the page they are viewing.

**Screenshot**
Here is a screenshot of the completion message appearing out of context (i.e. a search made after the fact):
![screen shot 2018-12-21 at 11 13 55](https://user-images.githubusercontent.com/14880206/50356999-9b52f980-0511-11e9-8f67-4e5bc47a6805.png)

**Comment by murny** [comment]
This is a good find. The reason for this is the "homepage" comes from the CMS and for whatever reason doesn't support flash messages (green or red alerts like you see in your screenshot). So you only receive the flash message when you go back into a "blacklight" page as only these pages support them. (this isn't caught in development as we don't have a way to run the site with the CMS)

So easy fix, we can just add flash messages support to the CMS layout:
https://github.com/ualbertalib/discovery/blob/master/app/views/layouts/cms.html.erb#L55-L57

which they should have had to begin with just like the blacklight layout has them:
https://github.com/ualbertalib/discovery/blob/master/app/views/layouts/blacklight.html.erb#L48

As an aside,  why do we have 6 layouts in Discovery (should only need one)....
https://github.com/ualbertalib/discovery/tree/master/app/views/layouts


Regarding your comment on "the completion message does not appear in place. Instead, users are redirected to the library homepage.":

I would say this is pretty normal behaviour for websites? After the user fills out the form, they hit submit and are taken away from the previous form to the thing they just created (e.g: I deposit a thesis in ERA, after submitting the form, I am now on the thesis detail page). Even the Email/Text/Corrections forms in Discovery all work like this. After submitting my correction, I am redirected back to the catalog item page. So we should probably remain consistent with the rest of the website?

Also not sure why you would want the user to remain on the form after submitting the form? They just submitted a request for an item. Do you want them to be able to submit multiple requests (I would assume you would clear out the form after a successful submission...otherwise you have other problems at hand like ability to submit the form many times, etc) ? You are just making it harder for the user, as now they have to use the navigation on the site (which all link back to the homepage anyways), or use their back button (a couple of times). Hence we can just redirect the user back to the homepage. Why do we redirect back to the homepage instead of the catalog item? Well these forms may not always have a corresponding catalog item as they can be independent of each other which was all defined in the requirements.

**Comment by seanluyk** [comment]
@murny thanks for the explanation re: the CMS layout etc. As for the second part of your message, I think I may have been misleading when I say in place. The behaviour should be the same as the other forms in discovery: once the form is submitted, return to the original item rather than the homepage. Hope this makes sense, and if not we can chat in the new year!

**Comment by weiweishi** [comment]
I believe this is been fixed and this issue can be closed? @murny can you please confirm?

**Comment by murny** [comment]
Don't think this has been deployed yet? Checked on staging and this fix isn't there. Once its deployed we can close this

**Comment by seanluyk** [comment]
@murny @pgwillia - not a huge deal, but in testing the behaviour of the BPSC form, I noticed that:
-When a form is submitted, the user is not returned to the referring page (i.e. the record view), but instead goes to a begin your search here page. Not sure if this is fixable but thought I would mention it

**Comment by murny** [comment]
This was part of the requirements when we built this. The forms (bpsc/rcrf) are not meant to be directly tired to catalog items as they were meant as general forms that could be sent to anyone and they could request anything even something not in our catalog. Otherwise  we would have tighten the two together (made the urls live under the cat key for example) and then we could handle these redirects smarter. 

With that said there could be opportunity to handle these smarter...if we have a valid catalog item redirect to the catalog item show page. Otherwise just render the root page ( .catalog index/search page). So something we can look into.
