### ISSUE TITLE
Create a manual checklist for acceptance test

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1599]
For acceptance tests. @seanluyk will work on a checklist for manually testing the discovery services.

**Comment by seanluyk** [comment]
@weiweishi  here's my attempt to document the various features to test (hopefully many of these could be automated). Please feel free to add anything I missed, and break these down further (some tests combined). Also, through coming up with these tests I'm noticing some inconsistent UI behaviour in places, so we can turn those into issues as we test, and I think we could remove some overhead by eliminating some of the expected behaviour in the UI/simplifying it:

|Feature |Expected Results|
| ------------- | ------------- |
|Search for "climate change"  | search results are returned (~11,000), number of search results are displayed under "you searched for", search query appears in Results returned for"", Access facet is autoexpanded, Google book image covers appear|
|Select top facet value in each facet from a query (if present) | clicking on facet label expands list, facet selections appear in "you searched for", search results decrease in number|
|Deselect facets, one by one from "you searched for"|facet selections should disappear from "you searched for", be deselected from left-hand facet, left-hand facet is collapsed
|Deselect facets from left-hand facet, one by one| facet selections are removed from "you searched for" and left-hand facet, facets closes upon deselection of facet value
|Limit results using publication range slider| from a list of search results, when expanding the publication facet, the range slider w/ historgram displays with the oldest and newest published date appearing in its respective text box. Dragging the left or right slider causes the dates to increase or descrease in their respective text box. Clicking on limit changes the number of results returned, causes the facet selection to appear in "you searched for", and causes the histogram display to change accordingly
|Page through results| paging through results using the previous/next labels (top and bottom of page) or page numbers (bottom of page) displays next set of results in list
|Return to search results from record page| Clicking on back to search results from a record page returns the user to the list of search results
|Start over from record page| Clicking on start over from a record returns the user to the library homepage
|Sorting search results| Selecting different sorting options (year, author, title) from search results reorders search results accordingly
|View more search results| selecting the option to view more search results at a time (50 or 100) returns additional search results               
|Bookmark a few items and view them; remove bookmarks| Clicking on the bookmark checkbox beside an item in search results and/or a record page results in a dialog box to appear ("Successfully added to bookmarks"). Clicking on Go to Bookmarks displays the selected bookmarks with the same fields that display in search results. Export options appear above list of bookmarks. Deselecting the checkbox beside a bookmark removes it from the list of bookmarks, and dialog box appears ("Successfully removed bookmark)
|Export results from Bookmarks| From the bookmarks page, clicking the email button brings up the email form. Submitting the form sends the item information to the user. Clicking on export to Endnote downloads an Endnote file for the item(s). Clicking on export to RefWorks brings up the RefWorks login page, and passes item metadata to RefWorks
|Export results from record page| Export functions from tools menu and holdings table function as they do from the bookmarks page
|Send Correction| Clicking on send correction link in tools menu from record page brings up send correction form. Submitting the form sends an email to the library helpdesk with item information
|Librarian View| Clicking on the librarian view link in the tools menu displays the MARC record in a popup window
|Request me| For BPSC and RCRF items that qualify, the request me button appears in the holdings table. Clicking on the button opens the appropriate submission form. Clicking on the submission form sends the request to the appropr
|View search history| Clicking on view search history from a record page or search results page leads to a search history page that displays recent searches in the current browser session. Clicking on clear search history returns a dialog box ("clear your search history?). Clicking OK clears search history, returns message "Cleared your search history", and removes search history from search history page
|View Citation| Clicking view citation from a record page causes a dialog box to appear with recommended citations in different styles
|Narrowing by subject from a record page| Clicking on a subject term from a record page initiates a new search for the exact term in the subject field. The subject term(s) searched are added to "you searched for" and to the subject facet (currently not the case). Clicking on different levels of hierarchy in a multi-term subject string adds successive terms to the query. Search terms are populated in the search box
|Narrowing by author from a record page| Clicking on an author term from a record initiates a new search for that exact term in the author field. The author term searched is added to "you searched for" and to the author facet. Search terms are populated in the search box

**Comment by weiweishi** [comment]
@weiweishi will capture this in di_internal, and will send to blacklight team. Where else should we capture this?

**Comment by pgwillia** [comment]
Could create a [github issue template](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) to use in release testing.
