### ISSUE TITLE
Verify library names and codes in the locations.yml

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#422]
Some still aren't coming through correctly.

See also #1117, #1127. Lots of tickets in OTRS about this too. Flagging as many of these as possible in the item records label.

**Comment by seanluyk** [comment]
Adding to this project as it's something I have in progress that should be done soon

**Comment by seanluyk** [comment]
@pgwillia I've added some files from Elaine that should hopefully help with this particular issue and potentially others that deal with the interaction between Blacklight and Sirsi Web Services:

https://drive.google.com/drive/u/0/folders/1mb5x0wOWMY6cfW6fsjS78gF1tjOQkzuj?ogsrc=32

**Comment by seanluyk** [comment]
Just adding a note that this, for the most part, appears to have been fixed after @nnunn updated this file. There was one missed dash in a location that will be added to the next release. We'll need to figure out how to keep this up to date/synchronized with Symphony and automated reporting for when it breaks

**Comment by seanluyk** [comment]
@nnunn could you also please verify/update https://github.com/ualbertalib/discovery/blob/master/config/statuses.yml when you have a chance?

Some locations/statuses are also not coming through (e.g. https://library.ualberta.ca/catalog/6636841) which appears to be using a - as a separator instead of an _ for the map cabinet location. Here's the most up to date file: https://drive.google.com/drive/folders/1mb5x0wOWMY6cfW6fsjS78gF1tjOQkzuj?ogsrc=32

FYI @weiweishi let's coordinate these changes for the next deployment and anything @pgwillia has been working on.

**Comment by seanluyk** [comment]
@nnunn - it appears that locations may be fixed in record views but not search results. Here's an example for BARD/RCRF: https://library.ualberta.ca/symphony?f%5Blocation_tesim%5D%5B%5D=uarcrf&q=trees

**Comment by nnunn** [comment]
I'll look at that. If you find tickets like this in the future could you assign them to me? Thanks!

**Comment by seanluyk** [comment]
@nnunn will do

**Comment by nnunn** [comment]
From an email conversation with Sean, Weiwei, and others:

We will need to discuss this but first impression would be we'd probably better off to keep that data in a database so that any change wouldn't need to require a new release. It seems to me that this change happens often enough, and requires work from both dev and ops team, it may warrant some new development to move it away from the yaml file. Do we have a ticket in the backlog for this?

Weiwei

**Comment by weiweishi** [comment]
From @kgood 

`Just a few words on how these codes change.

Every time we add or delete a library in Symphony these codes will change.  I believe they also change when libraries rename (which happens surprisingly a lot)  The software does not allow us to do this work in house and it has to be a purchased service via SirsiDynix. As was pointed out, the vendor does sometimes reuse old codes.  So the basic work flow is:

1. We request a quote from our sales rep for the services in question (name addition/deletion/change)
2. Invoice paid and work order of some sorts get sent to SirsiDynix staff
3. SirsiDynix let's us know the day this work will be done
4. Work is only done on the production server.  As the test server is always cloned from the production we never will do this kind of work in test first.
5. Changes take effect with the early morning halt and run of all Symphony services.

Two other places were we need to change these codes as well - the pick up locations in Elibrary, and the pick up locations in My Account.  If this ends up in a databases, we may then be able to directly query these codes from My Account which would be handy.  

One last thing, Elaine just mentioned that if we have some sort of web based admin for this, perhaps entering these new/changed codes would just be a task for her or another member of the sirsi team.`

From @nmacgreg 
`A minor implication for the playbook, if this goes ahead:  a (new) MySQL userid that can read from this database
It seems Rails can handle the idea of multiple databases, eg: https://www.thegreatcodeadventure.com/managing-multiple-databases-in-a-single-rails-application/
`

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation. These are are to date now, we'll just have to fix changed ones as they come up, in lieu of the db solution
