### ISSUE TITLE
Author search

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#533]
Looking for all the works written by Kiera Cass in the catalogue I used advanced search and typed the author name in the author field. While the results retrieve Kiera Cass' work at the top it also retrieves work by other people called Kiera or Cass - which makes it clear that without further indication this search does an "OR" search rather than an "AND" search. I know the sidebar says to put + symbols in front of the terms that must be located in the field but this may not seem obvious to users. I wonder if perhaps these searches should be AND searches by default?

**Comment by fculpepper** [comment]
I'm having the same issue when searching from the main search as well. Can we change the default to AND instead of OR for both the main and advanced searches? It makes it difficult to find known titles (a common Service Desk question).

**Comment by redlibrarian** [comment]
Blacklight/Solr doesn't really use AND and OR (it uses a different kind of indexing). I tried doing a few different searches: kiera cass, "cass, kiera" and kiera AND cass in the advanced search, and the same (correct) four titles always appear first in the list. It seems to me that the objection is that the list of results contains other, less relevant titles. One of the things that newer discovery systems has moved away from is the idea that a single precise list with no false-positives is necessary. According to various studies, users tend to skip the things that aren't relevant, and since the relevant titles appear first in the results list, this seems to be acceptable behavior to me, especially since the alternative ways of searching ("cass, kiera" and kiera AND cass) exclude the non-relevant results. One of the design decisions we made at the beginning of the project was not to change default Blacklight behaviour if the existing behaviour was acceptable (even if not perfect in all cases). 

The simple search behaviour is not quite as good with simple text searching, but then it is meant to be a more general search. Searching both "cass, kiera" and kiera AND cass again returns the correct four titles. Instead of changing the behaviour, and given that phrase searching and boolean operators should already be part of training and communication, I would suggest that precise author searches could be done in this way. This gives us the required behaviour without changing the defaults, which could have unintended consequences.

**Comment by sjshores** [comment]
It seems to me that the find more by this author link is not searching at all but instead presenting the entire database.  I get the header "results for in all library collections" and  1 - 25 of 5,674,410, which is the whole Symphony database. It should have said "results for [author's name] in all library collections".

**Comment by redlibrarian** [comment]
OK. I've modified this to use the new author facet to facet from within a record.

**Comment by hannepearce** [comment]
This appears to be resolved. A search for Kiera Cass provides the proper results in basic search. Advanced search is still not working (I get 5,664,824 results)
