### ISSUE TITLE
Object type/ general materials designation

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#534]
I believe that the **object type** field is taken from the GMD as is, but this would look better if the brackets and other punctuation were removed. For example, [this record, which everyone has] (https://search.library.ualberta.ca/catalog/2546715).

**Comment by redlibrarian** [comment]
This will probably require writing a custom indexing script to strip the punctuation and brackets from the source data field. I'll look into it.

**Comment by seanluyk** [comment]
Excellent, thanks @redlibrarian

**Comment by redlibrarian** [comment]
@seanluyk Does this look right now?

**Comment by seanluyk** [comment]
@redlibrarian Looks better, but I looked at a few other records and there's still some noise, for e.g. https://search.library.ualberta.ca/catalog/7092515

Not sure what should be done with the GMD. It's useful, but if the format is accurately captued in the format field, maybe this is duplicating it? Not sure what others think...

**Comment by redlibrarian** [comment]
Oh, now that I look at both these records, neither of them is cleaned up. I think this is due to there not having been a reindex yet. Still, yes, maybe we should decide whether both Format and Object Type are useful....

**Comment by theLinkResolver** [comment]
I can help with the distinction between "format" and "object type". The "format" field contains a term based on the type of content that the record is describing - for example: book, serial, music score, map. The "object type" field is basically telling you about the medium - for example: electronic resource, microform, sound recording.

So for an electronic journal, the format=journal because that's what the content is. The object type of electronic resource, on the other hand, tells you something about how you will view it.

So, too, with a microfiche reproduction of a book, where the format=book because that is what the content is.  The object type of microform tells you what the medium is.

@redlibrarian Related: How are things faceted into online vs. not-online?

**Comment by redlibrarian** [comment]
@theLinkResolver Basically, it takes a look at the locations, and if it contains a location of (e.g.) UAINTERNET then it's tagged as electronic, if it contains a location of (e.g.) UAHSS then it's tagged as print. The facet is multivalued, so if it has a location of UAINTERNET and a location of UAHSS, then it's tagged as both print and online. The mapping is here: https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/translation_maps/electronic_map.properties

I just did a basic stab at what was an electronic location - this might need some cleaning up.

**Comment by theLinkResolver** [comment]
@redlibrarian Very practical - the issue of records with both formats was one of my concerns and that solves it quite nicely!  

Now, I acknowledge that lots of those other NEOS libraries don't have the separate internet "branches", so there would be online things mixed together in the location that has been coded as "print". But since this interface is all about UA users, that's not likely to cause too much concern (although maybe some confusion with interpreting results - if someone sees Red Deer's online stuff showing up when they've faceted to print, they might think something is wrong. We can explain this in the training.)

**Comment by theLinkResolver** [comment]
@redlibrarian Still seeing the brackets for the object type/GMD. 

In the long run, I might have a better source for the information this field is trying to convey, but it ties in to our future work on format mapping.

**Comment by redlibrarian** [comment]
@theLinkResolver @seanluyk The brackets should be gone in the next release. Looking at the data, however, it's really quite messy. There's only so much cleanup I'll be able to do. This might need to become a cataloguing project.

**Comment by seanluyk** [comment]
@redlibrarian @theLinkResolver  - this is still a messy problem. In the past, the GMD was more necessary I think, and was displayed right in the title field. They dropped it in RDA for a reason, so I wonder if it's really only necessary. To me it's quite duplicative (e.g. sound recording (GMD) musical recording (object type)). Isn't electronic access covered by the access facet, and implied by the availability of a link, and the library location?

**Comment by seanluyk** [comment]
For example, in [this record](https://search.library.ualberta.ca/catalog/4881624), it isn't all that helpful to even have the GMD there. I agree with @sjshores 's comment in another issue that moving access links up would go a long way in improving usability

**Comment by redlibrarian** [comment]
@seanluyk @theLinkResolver I think GMD is probably redundant with everything else we have in place. I guess the only counterargument would be if there are some GMD values which are not mapped to anything else, so the GMD field is the only place to see them. If that's not the case, then I move we remove the GMD from the record view.

**Comment by seanluyk** [comment]
I'd gladly see this replaced by the content, media and carrier types that RDA has to offer, or if this could be replicated using existing AACR2 data at some point.

**Comment by theLinkResolver** [comment]
At this stage, we cannot drop the GMD (example: https://search.library.ualberta.ca/catalog/4014448).

The content/media/carrier fields could help us in the future, although combined media records (e.g. print+microform together) distort things. There is a MARC fixed field that could do the job but its position is variable (dependent on other fields), making it a medium-term consideration due to the display logic.

**Comment by seanluyk** [comment]
Ah, that's a really good example @theLinkResolver.

**Comment by theLinkResolver** [comment]
@seanluyk Thanks. I will be pleased when we can move beyond the GMD...

**Comment by redlibrarian** [comment]
How does this look now...? @seanluyk

**Comment by seanluyk** [comment]
Looking much better now - I tried this on a vareity of GMD types, and it's looking pretty good. There's the odd one with weird punctuation still, but for now, I think this is good enough
