### ISSUE TITLE
'Dark Storage'

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#536]
Dark storage items are showing up when they should be suppressed, see [Contributions to mineralogy and petrology] (https://search.library.ualberta.ca/catalog/459731). All the items that don't have the status "On shelf" are in dark storage and not requestable, here's the [iLink] (http://www.library.ualberta.ca/permalink/opac/459731/WUAARCHIVE).
Also, the holdings are crazy out of order, can they be ordered chronologically?

**Comment by redlibrarian** [comment]
I'm going to break these out into two issues. The first issue is the problem with Dark Storage. This seems to be a data problem. I will check in with Sandra about that.

**Comment by theLinkResolver** [comment]
Sam, this relates in part to problems with how shadowed locations are dealt with.  STOR_DARK, MISSING, IN_PROCESS, DISCARD being common examples in the catalogue.

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver - the problem seems to be that, while items are shadowed properly in Symphony and in the extracts we use for EDS, they are still coming through in Blacklight. This is doubly-weird in that, when I check the Web Services XML that I'm using to build the item table, these items don't appear there (i.e. are properly shadowed) - so I'm not sure where this data is coming from...

**Comment by redlibrarian** [comment]
This should be fixed with the changes to the way holdings are handled. See issue #581 .
