### ISSUE TITLE
PDF full text links

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#541]
When you click on the PDF Full Text link from the search results, you get an [error page] (https://search.library.ualberta.ca/articles/afh/108664897/fulltext)
I searched everything and then went to View all articles.
![image](https://cloud.githubusercontent.com/assets/14892870/10207392/2e9f4f4c-6789-11e5-99b3-71b14c3688a6.png)

**Comment by redlibrarian** [comment]
I'm a little concerned that EDS has changed their API and this is causing problems...

**Comment by redlibrarian** [comment]
Hm. Now that I've dug a little deeper, it looks as though this could be a problem with authentication. I wonder if the full text PDF links will need to be proxied...

**Comment by redlibrarian** [comment]
Changing this is extremely tricky due to EDS' authentication requirements. At some point we will need to dig deeper into the whole EDS authentication question, but for right now I've turned off full text direct access from the results screen. A user will have to click through to the EDS record to get the full text. However, they can see that full text is available from the results screen. Hopefully that is sufficient for now and we can revisit the whole EDS question down the road.

**Comment by fculpepper** [comment]
The PDF link is indeed gone and replaced by "Full Text Available". However, this note only appears on those articles available through EDS, articles we do have access to but users have to go through Get It to find the full text don't have this notation. I'm afraid users will assume that full text of articles is not available if they don't see "Availability: Full Text Available". 
By way of example, all 3 of these articles are available full text via UAL, but it kinda looks like just the first one is:
![image](https://cloud.githubusercontent.com/assets/14892870/10679664/4b440048-78d7-11e5-8aba-4f8a42a2ffc7.png)

Maybe better without the notation at all?

**Comment by redlibrarian** [comment]
@fculpepper I think you're right. I've suppressed it now - it will be gone in the next release.

**Comment by fculpepper** [comment]
Yep, it's gone! Looks good.
