### ISSUE TITLE
Phrase searching not working properly

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#545]
Phrase searching does not seem to be working properly. For example, [a search for "Die Forelle"](http://search.library.ualberta.ca/results?utf8=%3F&q=%22die+forelle%22) returns only 13 results in books and more, but it is contained in 197 items in iLink.

I suspect that the phrase search is not searching all index fields (such as contents notes), where this information is contained. Is it only searching title fields?

**Comment by redlibrarian** [comment]
No, all searches search all fields that have been set as searchable. contents_tesim, which is the content field, has been added to the default search field. That will make the text searchable. I'm not sure if the problem is with phrase searching, or if it's a question of what fields are being searched. Phrase searching seems to work in other cases. Anyway, take a look at the next code release and see if this problem has been resolved by adding the content field to the list of searchable fields.

**Comment by seanluyk** [comment]
This is still an issue - a search for "Die Forelle" still only returns 13 results in books and more, when it should be around 198, as this phrase appears in contents notes of score anthologies, larger works, etc.

As expected, taking the "" away returns more results, so I'm not conviced that phrase searching is looking in contents_tesim

**Comment by redlibrarian** [comment]
Hm. Something weird is going on. When I do a search for "die forelle" (phrase search) in the direct Solr interface to the index, I get back 198 results, and it is searching the contents_tesim properly. This is only one away from the Symphony result list, which is pretty good. When I search in the blacklight interface, though, this doesn't work, though the results should be the same. Strange - I'll have to dig into it.

**Comment by redlibrarian** [comment]
OK, well here's what it looks like is happening: when I do a search in the Solr admin for q="Die Forelle" I get the 13 results that Blacklight gives. When I do the query fq="Die Forelle" (a facet query), then I get back 198 results, all of which are relevant. So, we either need to loosen up the q search or somehow figure out what the fq search is doing so that we can get that functionality in Blacklight...

**Comment by redlibrarian** [comment]
I've changed the "mm" field back to what it used to be. This looks a little better in dev (not on a full dataset), so I'm going to have Henry modify the test index to see how that looks.

**Comment by redlibrarian** [comment]
This still isn't working in the test interface. I'll have to keep investigating.

**Comment by redlibrarian** [comment]
@seanluyk Can you take a look at this search again. Between the bento redesign and the indexing tweak, I'm now getting 161 results in "Books, media, and more" and 748 results in "Articles, books, and more". This is different from the 198 results we were looking for, but better than what we were getting...

**Comment by seanluyk** [comment]
@redlibrarian this looks much better. I limited by format to musical score and did the same thing in iLink, and the results are nearly identical (20 in Blacklight, 19 in iLink)

**Comment by redlibrarian** [comment]
OK, great, thanks @seanluyk . Can we close this issue, or does it need more refining?

**Comment by seanluyk** [comment]
I think it's safe to close, this is working very well. I tried it with another phrase likely to be buried in contents notes, and it's only 1 result off.
