### ISSUE TITLE
UI enhancement suggestion - location and call number display in results list

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#552]
It may improve usability if there was a little more information in a results view, such as indiciating library location and call# in the brief record displays.

I realize that users can get to this by faceting, so I understand that this may be more of a design choice than an issue.

**Comment by fculpepper** [comment]
I agree. When looking for a copy of a title that numerous NEOS libraries have, students want to know quickly where the closest copy is. Having to click into a record to see if it's available and which library is too time consuming, I would go to NEOS where you can scroll down a list and see where it is available and what it is (book, video, etc):
![image](https://cloud.githubusercontent.com/assets/14892870/10235674/b29f9a90-685b-11e5-9284-2a22b6078276.png)

**Comment by redlibrarian** [comment]
Hmm. I had already added a locations list in the results screen, but that isn't appearing. I'll investigate that. As for the format/item type - that's already listed in the record list metadata.

The issue with displaying a full location and call number table is that, due partly to the fact that ours is a consortial catalogue, and partly to the fact that we have such extensive holdings, especially of serials, that the table would be too large for effective result list browsing. We can display owning locations, but which call number would we choose, given that NEOS libraries have different call numbers? We originally displayed the basic LC call number, but that was removed since it was deemed confusing (because it didn't match the actual call numbers associated with individual items). 

Anyway, I will figure out why the locations aren't coming through and when they're back, I'll ask you to see whether they fit the bill or not.

Thanks.

**Comment by redlibrarian** [comment]
I had this logic in place, but it broke somehow. Working on it now.

**Comment by redlibrarian** [comment]
OK, it's fixed now, and uses the same logic as the other holdings data. This may end up being a little slow - we'll have to keep an eye on it.

**Comment by fculpepper** [comment]
Is this fixed? I'm not seeing it. (For service desk interactions, the call number isn't as important as the location.)

**Comment by redlibrarian** [comment]
Sorry - it will be visible in the next release, which should come out early next week. I'll send an email to the group when the new code is in place.

**Comment by redlibrarian** [comment]
Related to #663

**Comment by redlibrarian** [comment]
OK. The locations are coming through on search.library now. As I've said (somewhere else?) there's no good solution to the call number problem, so we'll have to discuss that in the new year. @seanluyk @fculpepper can you take a look at a results page and, if the locations are coming through to your satisfaction, close the ticket? Let me know if there are any problems.

**Comment by seanluyk** [comment]
I like how 'copies available at' displays. Even without the call number, this at least directs users to the appropriate library to retrieve the item or ask questions. @redlibrarian is this only showing on shelf copies (i.e. not copies checked out)? That would be ideal, but not crucial at this stage.

**Comment by redlibrarian** [comment]
Currently, this shows all copies, checked out or not. It can be changed to show only on shelf copies, but adding more logic (i.e. suppressing no loan, etc) would be tricky. Since that's a non-critical enhancement, I'd like to close this issue, and create a new one just for that issue to be tackled in the new year. Does that sound OK? @seanluyk @fculpepper

**Comment by seanluyk** [comment]
@redlibrarian Sounds OK to me - it's currently quite straightforward

**Comment by redlibrarian** [comment]
Closing. I think this is sufficient for now.
