### ISSUE TITLE
Call numbers with additions (e.g. folio)

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#559]
It looks like call number searching is mostly working, but not ranking results properly for some items with call numbers that have additions (e.g. folio, maps, study guide, etc.)

[Here is one example with a folio addition] (https://search.library.ualberta.ca/catalog/842764). 

Not sure if this issue is specific just to this record. It may have something to do with the fact that this title has multiple holdings. I've tried searching for other folio items and they are ranked first in results.

**Comment by redlibrarian** [comment]
I think I know why this isn't working. The indexed call number is the LC assigned call number in the bib record. The "folio" call number is one we've assigned, and are displaying using the Sirsi Web Services. Not sure how best to deal with this, unless there's a way to index item-level call numbers. @theLinkResolver do you know the MARC field for item level call numbers?

**Comment by theLinkResolver** [comment]
@redlibrarian The 090 fields (there can be quite a few) contain the call numbers as used at the item level, and those should be indexed instead.

Related to #602 and #552 call number issues, what are you using for display in search results?

**Comment by redlibrarian** [comment]
@theLinkResolver Thanks for the information. I'll see if I can index the 090s. There's still the question of which call number we pick when we can only display one, since (afaik) each UA library can have different ones. 

Wrt the search results - I *believe* that's taken from the *first* call number Solr finds in the record. I think this may be arbitrary, depending on the order Symphony attaches item records to bib records. In the individual record view, the whole status table is done using a live lookup against Symphony.

**Comment by theLinkResolver** [comment]
@redlibrarian You're right that there are multiple call numbers in use across the branches (it's avoided these days, but it happens, and happened a lot in the past).

As to which call number to display, I caution everyone that it's going to be impossible to find a way to display the most-desirable call number in the search results in every instance.  Even if non-UA numbers are filtered out, you can conceivably have a record with a different call number for each of HSS, BSJ, Augustana, and the microfilm version, for example.

Assuming that most would prefer to only see the call number if it's correct/useful, I offer this idea -- have the call number display only if there is one 090 field with $b=AEU (meaning only one UAL call number).  (Although, @redlibrarian, if you are saying that the call number in the search results comes from the item records rather than the bib record, then I guess you would only display it if there is one UA item. This is more limiting, of course.)

**Comment by theLinkResolver** [comment]
@seanluyk @redlibrarian I think the original issue described here exists because it is the second 090 field that contains the HSS call number (M 1003 P67 I37 1938 folio), so a call number search is not finding it. Only the first 090 (Augustana in this case) is currently indexed (M 1003 P68 I52 1938). So, this will be fixed with #854, when all 090s get indexed - @redlibrarian I think we can close this issue, then.

(The other issues discussed above re. choice of displayed call number are no longer a concern, since we have decided not to display call numbers in the record and results views, since it is impossible to decide which call number to display.)

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver
