### ISSUE TITLE
General notes spliced together

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#561]
The splicing together of general notes is a bit unsightly at the moment. Rather than a comma, maybe we can find another character (or string of characters) to serve as the visual break between 500 notes, if they are to remain combined.

e.g. https://search.library.ualberta.ca/catalog/3540530

![notes spliced together](https://cloud.githubusercontent.com/assets/14913579/10258687/7eaf84bc-691d-11e5-8a45-853b9c9a665f.jpg)

**Comment by redlibrarian** [comment]
Sure. I guess we could see if the note already ends in punctuation, and if it does, replace the punctuation with a semi-colon. If it does not, just add the semi-colon.

**Comment by theLinkResolver** [comment]
That sounds like a good solution. For the distant future, we might also be able to help identify some notes that could be filtered out, if that's possible (e.g. "Title from screen").

**Comment by redlibrarian** [comment]
OK, because the fields are constructed in the index, we don't have quite as much control over the display as I thought. I've added a 'space--space' separator to both the general note and local note fields. It doesn't replace the period, but it should give a sense of separation. A general note will now look like this:

Title from cover. -- Provides information on sources cited in three MEDLARS files: MEDLINE (including the backfiles), Health Planning & Administration, and POPLINE. -- "PB83-180851", etc.

This will be visible with the next code release - let me know if that's not an adequate fix.

**Comment by redlibrarian** [comment]
Huh. This should be fixed, but isn't. Again, I think this is due to a reindex not having taken place...
