### ISSUE TITLE
"Library has" field in record display (derived from 856)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#562]
I'm wondering if the "Library has" field might be an unnecessary field in the record display, as it seems to be derived from the 856 field, which also appears nicely as a button below the bib record.

e.g. https://search.library.ualberta.ca/catalog/690517

![library has in record](https://cloud.githubusercontent.com/assets/14913579/10258897/b1874256-691f-11e5-8d8c-1253a4764260.jpg)

**Comment by redlibrarian** [comment]
@theLinkResolver The "library has" note doesn't come from the 856, it's actually constructed out of all the MARC holdings statements in a record. Sometimes, that might correspond to an 856 label, but in some cases it won't. A better example might be: http://search.library.ualberta.ca/catalog/2693606 which is a print-only journal that still has summary holdings. Because summary holdings statements are tricky, there are still some discrepancies in the records (especially when a record is both print and electronic, which I understand will be going away soon).

I *personally* think summary holdings statements are unnecessary and non-intuitive, but this is something that has always been asked for in serials records. 

Maybe we should revisit this post launch and see if it's useful or a problem.

**Comment by theLinkResolver** [comment]
@redlibrarian I think we are looking at two different "Library has" notes here.  There is the one that appears amongst the fields of the record, which matches the contents of 856 $3.  (and I think it could be dropped from display)
![library has bib](https://cloud.githubusercontent.com/assets/14913579/10289598/5c2de2c6-6b5c-11e5-92f9-593ae29153f1.jpg)

Then there is the one you are talking about, appearing just above the items table, which is from MARC holdings.
![library has marc](https://cloud.githubusercontent.com/assets/14913579/10289642/a3e304ac-6b5c-11e5-91f9-4dcaf26abc1e.jpg)

We are post-summary holdings as a displayed necessity in many ways, but indeed, this example above shows how summary holdings is sometimes the only place our holdings are identified (and that's probably why you had it handy!).

**Comment by redlibrarian** [comment]
@theLinkResolver Ah, OK - I didn't notice the redundant label. I'll remove it (I'm sure I didn't see it before, weird).
