### ISSUE TITLE
OR  searches not adding up

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#567]
Apologies if I'm misunderstanding how this is intended to work, but I've noticed that OR searches seem to not be returning more results, which is the behaviour I am expecting.

For example, a search everything search for...:

*glam rock: 22974 results for glam rock
*glitter rock: 23101 results for glitter rock
*glam rock or glitter rock: 23153 results for glam rock or glitter rock

Should the last search not result in more results? I know that an OR search never equals the totals of the 2 strings, but in principle it should mean more results. Does Blacklight do some de-duplication or something?

**Comment by redlibrarian** [comment]
This is in simple search, not advanced search, is that right? Boolean operators aren't enabled in simple search, as they break other functionality, and the information retrieval behaviour of Blacklight isn't intended to be used with boolean operators. Boolean has been added to the advanced search primarily for librarian use. Searching glam rock will find both terms in all fields, then use relevancy ranking algorithms to determine the order results should be presented. It's not exactly an and search, because if the term glam appears in a heavily weighted field (like title), but rock does not, it is likely still in the list of results. Similarly with glam rock glitter rock - the three search terms are used to build the result list, but again it's not strictly ANDing or ORing the terms. Adding the word 'or' is treated by blacklight as a fourth search term, though since (I think) it's already in the list of stopwords, it should be ignored at that point.

**Comment by seanluyk** [comment]
Yes, in simple search. Thanks for the clarification, Sam, this is really helpful. We will need to include an explanation about this in our staff training, as I think many of us were expecting that operators worked the same in both simple and advanced searches. However, as long as everyone is aware of how relevancy is weighted (basic principles), we can better instruct users on how to get the best information out of the system.

**Comment by seanluyk** [comment]
Now that I know that Boolean isn't working in Blacklight as I was anticipating, I think that this is no longer an issue and can be closed (it's also discussed elsewhere).

**Comment by redlibrarian** [comment]
OK, thanks @seanluyk . Let me know, though, if the discussion we have around searching doesn't answer this, or raises any other issues. I'll close this for now.
