### ISSUE TITLE
Adding facets in article view - "Y" appearing, not label

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#576]
It looks like facet values (y/n) are appearing instead of the facet labels.

Here's what I did:
1. Searched for something in simple search
2. Clicked to see results in articles container
3. Selected a number of facets under limit your search (all seem to not be showing facet labels in the facets box above the list of results)

**Comment by redlibrarian** [comment]
I think this is high priority, as it may actually break the faceting system.

**Comment by redlibrarian** [comment]
Ok, so it turns out this wasn't really high-priority as it didn't break the faceting system. I tried to get the EDS interface to display "limited/nonlimited" information properly, but the way EDS handles its parameters, this wasn't possible without spending a lot of time and reprogramming on it. What I decided to do is to remove limiter information from that panel - since you can see what limiters are selected right next to the panel, it seemed redundant. The panel now displays facet information, but not limiter information, and does not display confusing information. I think this should be sufficient for now. We may want to look at this again later. The change will be visible in the next code release.

**Comment by seanluyk** [comment]
The panel is no longer displaying y/n when adding facets
