### ISSUE TITLE
Blanks and weird stuff in advanced search facets

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#602]
1. **Library**: there are some blanks

2. **Call Number**: lower case letters, punctuation, numbers

3. **Format**: Where are these coming from? There are many similar things listed multiple times

4. **Time Period**: mixes eras and year ranges. Is this avoidable?

**Comment by redlibrarian** [comment]
Library: I think these blanks are due to the labeling problem in issue #581 .

Call number: this is a data/indexing issue. @theLinkResolver and I need to discuss this further.

Format: These are drawn from the data we have in Symphony, SFX, and the database of databases. This may have to go to cataloguing for cleanup.

Time Period: I'm not sure where this is coming from. Is Time Period even a useful facet?

**Comment by seanluyk** [comment]
Re: time period - I'm not sure how useful this is either

**Comment by theLinkResolver** [comment]
@redlibrarian To answer the question of where "time period" comes from, it's coming from geographical subdivisions ($y) in the subject headings.

**Comment by seanluyk** [comment]
@redlibrarian @theLinkResolver should probably retract my previous comment. I do think it's useful, and it's too bad that ranges and eras are mixed. Are eras and ranges coded differently at all? i.e. is it possible to sort them differently?

**Comment by redlibrarian** [comment]
@seanluyk @theLinkResolver The Time Period values are populated from the 650$y, 651$y, 654$y, 655$y, and it's just using the straight data, so I think the mix is due to the underlying data. It might be possible to map that data to values/labels that are more consistent, but I'm not sure a) how much work that would be and b) how consistent our data is to begin with (which it would need to be in order to accomplish this). However, maybe having all of the 650, 651, 654, and 655 fields is causing the problem and we should only use a subset of these...?

**Comment by theLinkResolver** [comment]
@seanluyk No, there is no variation in how these are coded, and there are a variety of forms.  "Time period" is as specific as it gets!  (MARC21 says: "The chronological aspect of subjects may be expressed in a variety of ways depending on the patterns that have evolved in the various fields.") And of course, lots of works don't have any time period specified, so this facet wouldn't apply to those at all.

**Comment by redlibrarian** [comment]
I'm going to close this issue. @theLinkResolver and I have identified some data cleanup issues that will hopefully be addressed in the new year.
