### ISSUE TITLE
Item with different URL not opening

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#608]
Clicking on this [ebook record](http://search.library.ualberta.ca/catalog/ocn917137039) results in a "something has gone wrong" page.

Noticed that the URL is a little funky on this one (with the ocn added). Item title is *Acrylamide in food*

**Comment by redlibrarian** [comment]
Ugh. This is due to a pretty ugly internal procedure we have. When we load brief (e.g. on order) records in Symphony, we use the record's own identifier (often an OCN number). When we load a full record either from OCLC or elsewhere, the brief record is replaced and the item gets a new, standard Symphony cat key (the usual record identifier). These ocn* records are usually only in our system for a day or two, I think, but systems like EDS and Blacklight that pick up those records and don't delete them can cause an error when trying to access them - they exist in the Blacklight index, but Blacklight checks for item location, status, etc, from Symphony and can't find the item. 

I thought these records were supposed to be caught quickly, but maybe our updates aren't happening fast enough. I'll have to look into the process.

Something else I should write in is for these records to fail gracefully rather than give an error message. I'll see what I can do on that front.

**Comment by theLinkResolver** [comment]
@redlibrarian I should add, fyi, in cases where we overlay a record with a new one, the non-standard catkey will hang around until the weekend, when a report runs to reassign the previous (normal) catkey.  So if I do an overlay on Monday, the 001 won't revert for several days under the current schedule.

That particular report was suspended from Aug 22-Sept. 21, so there were maybe even more records like that in the system than usual, during that time period.

**Comment by redlibrarian** [comment]
Addressed in #685 . Closing this ticket.
