### ISSUE TITLE
Add 856|3 as note field for discovery of NEOS Library Consortium Access collection.

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#634]
I wanted to filter for just the new NEOS ebooks that we recently added to the catalogue (to show a faculty member) so I went into advanced search and searched for "NEOS Library Consortium Access" which according to Anne C-W is the label being put on these records. I tried it in the "All Fields" field of advanced search, first with quotations then without and the search results were not what I wanted. Perhaps I'm not understanding what the "All Fields" box is searching - I'm assuming it's the entire bib record. 

I then tried to use facets by limiting to online and library. I discovered there is a link in the library facet but it is appearing strange.
![2015-10-15_17-30-31](https://cloud.githubusercontent.com/assets/14892833/10530314/b7e17236-7363-11e5-9b24-303e2f19dfbe.jpg)

Also when I click on this facet the search results are not what I am looking for (the first few items in the list are either free internet resources or ebooks at one or a few NEOS institutions). Perhaps this isn't a high priority issue but I should be able to do an all fields search for a bit of text to find certain types of items.

**Comment by redlibrarian** [comment]
Thanks @hannepearce . There are two separate issues here. The second one (the problem with the library facet) is one that I'm already tracking down elsewhere. The first problem is due to the fact that "NEOS Library Consortium Access" isn't used in any kind of local note field, which is indexed by Blacklight - we're using this to allow people to search for specific collections. "NEOS Library Consortium Access" is the label used for the 856 link to the ebook - not a field that we would normally index for search. This is searchable in iLink, so whether we want to make the 856 labels searchable is up for discussion. 

One other thing I'd like to address is what "all fields" means. In Blacklight, the concept of a "bib record" becomes tenuous as a) MARC records aren't used in the index (the fields we specify for search and display are taken out of the original MARC records and put into non-MARC XML records) and b) more and more of the things we'll be indexing in Blacklight aren't MARC/catalogue records (e.g. databases, ERA records, curricula in MODS format). So "All Fields" in Blacklight means "All Fields" that we've defined as searchable.

I hope that clears a little of that up. I'll think about whether indexing the labels of the 856 field is useful, and as I say, I'm still tracking down the library facet problem.

**Comment by redlibrarian** [comment]
@sjshores Do you know how often we use the 856 label rather than a local note for a collection name? I realize that in this case it's so that people can see "NEOS Library Consortium Access" on the link they click on to get the ebook, but do you think there are other cases like this? Rather than indexing the 856 label for search, it might be better to index that label as a note. "NEOS Library Consortium Access" will still appear as the link label (though right now they will be excluded if there's a UA link as well, similar to other non-UA NEOS links - is this acceptable functionality for the NEOS Library Consortium Access books?)

**Comment by sjshores** [comment]
Sam, this is the only collection where the 856|3 tag has this kind of
meaning.  It would be nice if the word NEOS or the phrase could be
searchable as a note.

Thanks,

Sandra

**Comment by redlibrarian** [comment]
OK, thanks Sandra. I'll see about tweaking the index to make this searchable.

**Comment by redlibrarian** [comment]
OK, turns out we were already using this field in another piece of code, so I've made it searchable. It should work in the next code release.

**Comment by theLinkResolver** [comment]
@redlibrarian in issue #562 the plan was to remove the 856 $3 from where it appears in the record view (since the same string of text appears as a clickable button).  Does the decision above change this?  (I just want to make sure it gets logged in #562 for our future reference, if that's the case!)

**Comment by redlibrarian** [comment]
@theLinkResolver Let me know if this is wrong: there are 2 "library has" fields, one of which is the 856/3 that we are going to remove (it has, in fact, already been removed). The other "library has" field is a constructed field that gives (or should give) a full date range across all subscriptions. Separate from these two fields is the clickable 856 link, which uses both the 856/3 and the url in its display. We'll be leaving both the second "library has" field and the clickable link in the record view. 

Wrt this issue, I'm going to be adding a new note field that also contains the 856/3, will be searchable, but won't display (since it would just display what's already present on the clickable link). This is just to make the 856 labels searchable.

**Comment by theLinkResolver** [comment]
@redlibrarian Check, check and check.  And thanks for clarifying on the solution to this issue.

**Comment by hannepearce** [comment]
@redlibrarian @theLinkResolver I'm working through my issues marked "check in next release" but not sure if this issue was expected to be resolved yet. A test showed that it's still not searchable - 
![university_of_alberta_libraries 4](https://cloud.githubusercontent.com/assets/14892833/10673713/77cae186-78b4-11e5-8e06-9dbb68adade1.jpg)

**Comment by hannepearce** [comment]
A search in the advanced "all fields" doesn't work as it appears the advanced search is broken (gives me 5,664,824  results). Doing a phrase search for "NEOS Library Consortium Access" works like a charm.

**Comment by redlibrarian** [comment]
@hannepearce Can you confirm whether it's working in simple search? I have another ticket open for the whole advanced search problem, but maybe we can close this issue if the search is working in simple search...?

**Comment by redlibrarian** [comment]
This should now be working both in simple and advanced search.

**Comment by hannepearce** [comment]
This is working now! yay!

**Comment by redlibrarian** [comment]
Yay! :)
