### ISSUE TITLE
Misleading note re: online access

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#636]
Hi. This note shows up for online resources at the bottom of the record:
"No University of Alberta Access. On-campus access allowed at the following locations:"
But, the University of Alberta Access link is there. In this case, the resource is an open access resource. 

Sean said he mentioned this as well, noting that not all NEOS Libraries provide onsite access to e-resources. They are supposed to under the NEOS agreement, but some of them aren't used to doing it. 

Since we have no idea how and when people are using the online tools, I'm concerned that the note could be confusing. Now that there are ebooks in the catalogue that are available NEOS-wide, and licenses and online access will continue to evolve, I'm wondering whether we should use more generic wording, or just not go there.
![no online access screenshot](https://cloud.githubusercontent.com/assets/14894185/10548565/f59f1e08-73f8-11e5-8a2e-983779bf7020.jpg)

**Comment by redlibrarian** [comment]
This is the same issue as #538 and has been fixed (will be visible in the next release). 

The logic that we have in place is as follows: When there is a U of A licensed link, or another link that we have access to (Free Resources, or NEOS ebook collection), then those links will display, but the links for other NEOS libraries *will not* display. When there is *no* U of A or free/NEOS link, then we *will* display the link for the other NEOS libraries (since, as you say, our users can go to the other NEOS libraries to use the resource), along with the note that there is no UA Access. This logic was chosen so as not to present UA users with non-UA links when a UA (or free) link is available. 

I hope that makes sense. It will be easier to see when the logic is fixed in the next release.

**Comment by redlibrarian** [comment]
@linds37 Can you check to see whether this is resolved now? If not, let me know what else needs to be tweaked. Thanks.

**Comment by theLinkResolver** [comment]
@redlibrarian @linds37 I tested a few different scenarios (UA only, UA with other NEOS libraries, free access only, free access with other NEOS libraries) and they all work. 

But... the note shouldn't appear for this one:
https://search.library.ualberta.ca/catalog/7093662

**Comment by redlibrarian** [comment]
@linds37 OK, thanks. I've added the "NEOS Free" material to the list of things we *don't* display the message for. That should work in the next release.

**Comment by linds37** [comment]
The example I gave above seems to be working now. It is confusing that you click on the big long url in the grey box, rather than on the blue "University of Alberta Access" link in the holdings info. Would it be possible in the next release to make it clearer where to click? Would it be possible for the title itself to be hyper-linked?

**Comment by redlibrarian** [comment]
I'm going to close this ticket as the underlying issue seems to be resolved. There's a plan to move the link to the top of the page so that it's clearer where to click.
