### ISSUE TITLE
Question: Search syntax, parameters, etc.?

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#648]
Hi. So, what actually happens when you do a search in blacklight? I'm preparing for a grad course and tried this search:

industrial revolution and (wom?n or gender or girl*) and (Great Britain or United Kingdom or England) 

It found some books and articles that are on topic. However, it looks like some of them are only partially on topic -- for example Industrial Revolution and England are covered, but there is no mention of women or gender or girls

How is Blacklight actually understanding the search string? If it is too complex, what would be a better way to express the three concepts in the search? Is there a way to only pull in results that match all three concepts in the search?

Here's another example search:

humanism and Habsburg Empire

- the results that come up mostly have Habsburg Empire somewhere in the record, but humanism hardly shows up in any, so the results are too broad and are not relevant. 
- leaving out the "and" produces exaclty the same search 
- searching with "or" provides the exact same search results for the Books boxes, but way more in the Articles box, which leads me to wonder if the OR search works for Articles, but not for Books

**Comment by seanluyk** [comment]
@linds37  - I agree that it's really important for us to understand how results are being ranked. I experienced a similar issue yesterday when looking for a score for a student.

Although I was able to find it within the top ten results, the huge number of results (many of which are not relevant at all) takes some getting used to.

I also wonder, @redlibrarian , if the relevancy threshold needs some tweaking, and if this is possible/advisable? It seems like we've maybe favoured recall a little too much over precision, although  the fact that what I'm looking for tends to appear in the top results makes me think that the precision bit is working.  .

**Comment by hannepearce** [comment]
I am adding to this question as I too am very puzzled by the relevance and ranking - especially in regards to simple search vs. advanced search -- Here in Education one of the MAJOR searches we do on a DAILY basis is combine a topic with the term *juvenile* (or juvenile fiction) it's how we find books in curriculum on particular topic. 

I am preparing to teach for EDPS 401/501 (LGBTQ Contexts in Education) and I've been practising searches both in simple search and in advanced. When I do the search "homosexuality juvenile fiction" in simple search I get 214,223 print book results, the first few of which are admittedly books about Homosexuality intended for a Juvenile audience but they are not fiction. Also a **vast** amount of our curriculum collection does not show up at the top (I worked with this part of the collection a lot so I know we have lots of story books and novels on the subject) -- by item 9 the result, the list has nothing to do with homosexuality and in fact the title is: *More notes from a different drummer: a guide to juvenile fiction portraying the disabled* <ak!> that could be seen in a bad light considering this search. Anyhow... when I repeat this search in advanced search putting the terms into the subject field I get the results I was looking for. 

I am concerned that this difference in the way the two searches work will be quite confusing for students and staff. I am also worried that students will only make use of the simple search and in fact not find many of the books we have because they are trusting the system would have shown them when they used the simple search...  I can teach me class to use the advanced feature - but I guess my point is that with the way simple search is configured currently it is not making things *more* discoverable - it's burying them.

**Comment by redlibrarian** [comment]
Thanks everyone. This is a *huge* topic, and combines a lot of different elements. I still need to work on a document for all staff explaining how this works, but let me take a stab at it here.

Blacklight uses an index called Solr (http://lucene.apache.org/solr/). This is what's known as an XML or document-index (i.e., it's not a relational database). It indexes XML documents created from all of the records that we put into it. There are two main configuration files for Solr, one of which determines whether fields are searchable, what kind of data they contain, whether they can be multivalued or not; and the other contains information about the actual search indexes (i.e. all-field search, title search, author search etc.). The *mapping* of our record fields to Solr fields is done outside of this Solr configuration, and is different for each kind of record (MARC record from Symphony, database record, etc). 

The configuration file that handles the indexes also handles the relevance ranking information. Basically, what it does is allows you to assign particular fields to an index (so we might assign our Solr author field to the author index) and then assigns a weight to that field. Solr relevance weighting is a pretty esoteric topic, but we can tweak this however we like. I've *mostly* left this configuration as it stands out of the box, except when we've needed to add new fields to an index. You can see what fields and weights are currently in the index by looking at https://github.com/ualbertalib/discovery/blob/master/solr/blacklight-core/conf/solrconfig.xml though, as I say, it's pretty complex/esoteric. 

Given that Solr is not a relational database, but a document index using weighting of fields to determine relevance, boolean logic does not apply when creating a list of results. Blacklight allows boolean operators in the advanced search by breaking the relevance logic a little, but they don't work in the simple search box. So @linds37 's boolean search string will see the "and" and "or" as query terms and will either search for them or treat them as stop words (depending on the stopword configuration). 

What I see in all three comments (and what I hear from a lot of librarians) is that you are used to being able to do a very precise search string to get a very precise list of results. This isn't how Solr/Blacklight works. Essentially, the search behaviour that should work best is similar to a Google search: starting with a general search and adding search terms or selecting facets in order to find the information you want. If you think about it, the fact that you get approx 121,000,000 for Shakespeare (for example) doesn't prevent me from finding what I'm looking for. Amazon works the same way: a general search for "Hamlet" gives me 31,753 results, but it's likely that - if what I want is not in the first few results - adding search terms or selecting facets will get me what I want. 

The move from boolean/relational index and search isn't an arbitrary one: the search strategies that we were taught in library school (at least I was, in 2005-07) date from a period when each database contained a relatively small number of records indexed according to specific metadata fields. The increase in computing power means that databases/indexes now contain millions of records and are full text searchable. The boolean logic/super-precise search leading to a precise result set is a thing of the past. The advanced search is really there to give you an approximation of that, but it does that by modifying the default behaviour. 

So with @hannepearce 's comment that "with the way simple search is configured currently it is not making things more discoverable - it's burying them", I think this is based on a view of discoverability as working the same as (e.g.) a Dialog database search, but this isn't the case. You may need to find new ways to get your students to the information they need. Perhaps a more general search like "homosexuality juvenile" and then clicking on the Fiction subject facet would be more help. It will require some exploration to figure out the search strategies that work best in this system, but a good rule of thumb is to try searching the way you would search in Amazon. That might not work, but it might be a good place to start.

I hope this is of some help. Let me know if this isn't at all what you were looking for, or if I can clarify/amplify things, or if you have further questions....

**Comment by redlibrarian** [comment]
One more thing: this isn't to say that the relevance ranking algorithm/indexes can't or shouldn't be tweaked, just that we shouldn't think that we can tweak them into giving us very precise result sets like we are used to getting in e.g. Symphony.

**Comment by merisjames** [comment]
I guess my major concern is that we are getting umpteen results that we don't expect... Google "ANDs" your terms, and will show any omitted terms greyed out with a strike through, so you know what you're not getting. It looks like here terms are being "OR"ed and then ranked. So yes, ideally good results still come at the top, but I'm not sure that we are improving our users' experiences by showing them every other result with (possibly) a single search term. It's a little overwhelming, and meaningfulness is significantly reduced.

**Comment by redlibrarian** [comment]
We should certainly tweak the relevancy ranking if searches are bringing back many irrelevant results high up in the result list, but we'll have to be very careful about how we define "irrelevant". Also, as I say, thinking in terms of "OR" and "AND" may not be that useful. Neither Google or Blacklight uses Boolean logic to combine search terms/determine a result set.

**Comment by redlibrarian** [comment]
Another way of thinking about this might be: instead of trying to figure out how to search in Blacklight, we should be thinking of how to find what we're looking for. This might seem like a subtly distinction, but I do think it gets at something important....

**Comment by redlibrarian** [comment]
Maybe one thing that would be useful is if we got together and looked at a few searches and we could talk through what Solr and Blacklight are doing to coming up with the result set. Would that be helpful/useful? @timwklassen what do you think - is there time for a meeting like this?

**Comment by redlibrarian** [comment]
Working on #545 , I've discovered that, I think, @merisjames was essentially right, and the matching algorithm was being too permissive with search terms. I've reset that to the Blacklight default (we had changed it a while ago to get what seemed like better results), and it seems to give better results on my workstation. The next step is to have Henry change that in the test index and then we'll see how that looks.

**Comment by linds37** [comment]
@redlibrarian Hi, Sam. One of my concerns is the scenario where there are very few or no items that actually contain the keywords that get searched. The example Habsburg Empire and humanism shows what I mean. I'll try again when you implement the change to the matching algorithm you just described. Right now, if you search for: Habsburg Empire humanism, there is really only one relevant result in English -- only a couple of the article records that come up have all three words in them. The rest have the words Habsburg Empire, but not Humanism, so on the book list, the researcher is only seeing false hits. When an old school search tool comes up with very few or no hits, this is a signal to the researcher that other avenues need to be followed - specialized databases, bibliographies, theses, etc. It will be confusing for the researcher to think a book is relevant, find it, then realize that the topic of Humanism isn't covered in it at all.

**Comment by redlibrarian** [comment]
Thanks @linds37 - judging by your description of the Habsburg Empire and Humanism problem, I'm hoping this fix will help with that. Let's take a look after the next release/reindex. Judging by some testing that I've done on my workstation, the number of false positives should be reduced with this change.

**Comment by dmc2** [comment]
I was at a conference this week and heard a very good presentation from someone at Ebsco who's been doing some large UXs testing (undergrads and doctors). Based on what they've found students are happy with billion results because they only look at top 3 and will either change terms or use facets to narrow. So I think Sam makes a valid point about how we need to re-think our search preferences as well.

Diane 

Diane Clark, MLIS, MEd | Staff Development & Training Librarian, Agricultural, Food & Nutritional Science Librarian | University of Alberta Libraries, University of Alberta, Edmonton, Alberta | e: diane.clark@ualberta.ca

**Comment by sjshores** [comment]
And focus on tweaking relevance to make those top results as consistently
as good as possible.

Sandra

**Comment by redlibrarian** [comment]
I'm trying a tweak to the search behaviour on our test server. Using the sample search **humanism habsburg empire** I get 110,855 "Books and More" results in the current live interface and 428 results in the test interface. This looks to me like an improvement: even though the last of the 428 results don't look relevant, there are fewer results, and the first results look extremely relevant. (As far as I can see, there is only one book in Symphony that contains both **humanism** and **habsburg empire** and due to an indexing problem, this isn't being returned, but that's a separate issue that should be fixed in the next release). So for this sample search, I think I'm seeing an improvement. I'm going to try the other searches mentioned in this issue and see what happens...

**Comment by redlibrarian** [comment]
Searching for **homosexuality juvenile** in the current interface returns 127,039 "Books and More" results, and only 104 results in the test interface. Searching for "fiction" is tricky - I doubt that field is being indexed for search. @theLinkResolver do you know which MARC field that is and whether we use that consistently?

**Comment by redlibrarian** [comment]
I'm going to leave this search functionality tweak in place in the next release. We can see whether it improves the results that you're getting.

**Comment by linds37** [comment]
Yes, that definitely sounds like an improvement. Juvenile literature and
Juvenile fiction are subject subdivisions in the 650 field, ie:
Homosexuality--Juvenile literature
<http://neos.library.ualberta.ca/uhtbin/cgisirsi/?ps=u5tKTpf3LN/UAARCHIVES/98250703/18/X650/XSUBJECT/Homosexuality+Juvenile+literature.>
(see,
for example http://www.library.ualberta.ca/permalink/opac/7033681/WUAARCHIVE
)
Homosexuality--Juvenile literature--Bibliography.
<http://neos.library.ualberta.ca/uhtbin/cgisirsi/?ps=T5Mgd6LQOM/UAARCHIVES/98250703/18/X650/XSUBJECT/Homosexuality+Juvenile+literature+Bibliography.>
(see,
for example http://www.library.ualberta.ca/permalink/opac/7128307/WUAARCHIVE
)

[image: Inline image 1]
<http://www.library.ualberta.ca/permalink/opac/7128307/WUAARCHIVE>

Lindsay Johnston, Public Services Manager & Subject Librarian
Rutherford Humanities & Social Sciences Library
<http://guides.library.ualberta.ca/rutherford> and Weir Law Library
<http://guides.library.ualberta.ca/law>
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta
T6G 2J8
780.492.0598

lindsay.johnston@ualberta.ca

**Comment by redlibrarian** [comment]
Ah, that's great, thanks @linds37 . If I do a search now for **homosexuality "juvenile fiction"** I get 71 results in the test interface, all of which look relevant. Compared to >50,000 results in the live interface. I think that's getting closer to what we need.

**Comment by redlibrarian** [comment]
Interesting - just for comparison, Symphony returns 78 results for **homosexuality and "juvenile fiction"**.

**Comment by sjshores** [comment]
Could it be that we've added some titles since the index was last updated
in Blacklight production?

Sandra

**Comment by hannepearce** [comment]
Yes it is very likely - as we just ordered a round of books on this subject a little while ago. @redlibrarian your test results sound promising!

**Comment by linds37** [comment]
@redlibrarian Hi, Sam. It would also be good to try the test server search with some searches that did have relevant hits at the tops of the lists before, to make sure they're still there, eg:
industrial revolution women England

At our meeting, I'm hoping we can discuss ways to incorporate searching for synonyms / related terms, eg: knowing that the concepts of women and England can be expressed in different ways, considering:
- singular, plural and closely related terms (women, woman, girls, gender, etc.)
- England as part of two larger wholes (Great Britain, United Kingdom)

Adding terms seems to dilute the search in Blacklight, but I'll be interested to see what the new algorithm does.

**Comment by redlibrarian** [comment]
@sjshores I'm pretty sure we don't have a fresh index. Kenton is following up.

@linds37 searching for **industrial revolution women england** produces 173 results in the test interface and 305,000 in the live interface. Reassuringly, the titles in the first page of results (25 titles) are almost exactly the same - there are a few titles that are different in each list, but I think the relevance still holds up. This will be something to check when the new tweak is made live next week.

**Comment by linds37** [comment]
that sounds really good. Thanks!!

Lindsay Johnston, Public Services Manager & Subject Librarian
Rutherford Humanities & Social Sciences Library
<http://guides.library.ualberta.ca/rutherford> and Weir Law Library
<http://guides.library.ualberta.ca/law>
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta
T6G 2J8
780.492.0598

lindsay.johnston@ualberta.ca

**Comment by redlibrarian** [comment]
I'm going to close this issue, as we'll be discussing it in person on Friday. Feel free to reopen if necessary.
