### ISSUE TITLE
Improved Error Handling for Web Services Outage

### ISSUE THREAD

**Issue by kgood** [ualbertalib/discovery#664]
As observed during our web services outage this morning, we need better error handling for when web services is not available.  As it now stands, the application will simply give you the standard error message when trying to get to hitlist or full record.  It would be great if we could still see the metadata (minus the holdings info) in such an outage event.  Sub topic - do we have a similar problem if the SFX api is down.

**Comment by redlibrarian** [comment]
Hm. This could be tricky, as essentially the web services time out, and I don't know of a way to check if web services are up beyond making a request which would just... time out. I wonder if there's a way to shorten the time out time, and then add logic to render the rest of the page on a time out. @pgwillia do you know if there's a standard or best-practice way to do this?

**Comment by pgwillia** [comment]
@piyapongch recently mentioned using AJAX to dynamically/asynchronously load page content. Might be applicable here. Downside is a dependency on javascript which is not a friend of accessibility.

**Comment by redlibrarian** [comment]
Thanks @pgwillia  - @piyapongch. Currently the web services request is server-side, and I think asynchronous calls are hard (impossible?) in Rails because it's only single-threaded (iirc). Would that mean we'd have to rewrite the webservices code to load client-side (with AJAX)?

**Comment by pgwillia** [comment]
rescue_from?

**Comment by redlibrarian** [comment]
This looks like it could work for us (at least, as a pattern), but they silently gloss over exactly how their Twitter exception works. All the example exceptions fail immediately due to some kind of problem, so I assume that their expecting something like an immediate 500 error from Twitter. I'm not sure we get this from Sirsi WS or SFX when they're down - @kgood do you know? If we do, then we could do an initial connectivity check and if we get a 500 error (for example) then we render the page without the dynamic content. If we don't get a sane error, however, and the request just times out, then we're back to square one - how do we either recover immediately from an error (i.e. setting timeout to some very low value) or render static content first and let the dynamic content load asynchronously....

**Comment by pgwillia** [comment]
Just wondering if anyone has any suggestions for how long to wait for timeout (10 seconds?) and language to display to the user when the service is unavailable ("Could not contact Symphony" / "Could not contact SFX").

**Comment by redlibrarian** [comment]
@pgwillia Good questions. For the timeout, @nmacgreg will have a better sense than me what our load times typically are. If it's tweakable, we could start with 10 seconds and see what that looks like? As for the messaging, I'd rather avoid using the names of behind-the-scenes services. How about something like "data temporarily unavailable" for both?
