### ISSUE TITLE
Non-EDS search APIs

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#668]
I've had some questions about whether or not it is possible for other search APIs (e.g. ProQuest, JSTOR, etc.) to be indexed and displayed in Blacklight search.

Are there plans for this in a future phase?

**Comment by redlibrarian** [comment]
It's not something that's come up, but it could be worth thinking about. The problem is that, like EDS, you won't be able to combine those results into a single index with anything else. You end up with a faceted search system, which libraries don't tend to use anymore due to the fact that they're a) slow and b) you can't connect one set of search results with another (in order to e.g. facet). We use EDS because we need to have *one* article KB in place. Whether adding more makes sense is a conversation we should have in phase 2.
