### ISSUE TITLE
"Start over" link generates random search

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#695]
Hi. I was just testing the new algorithm. Seems to be working well. When you click on the "start over" link at the top of the search screen, it brings you back to the bento box screen with a random search in it and it says, eg: 7835143 results for [blank].
It would be better to go back to the main search page, or to blank bento boxes, if that is possible.
I'm not sure if the "start over" link is necessary, since there is a "search again" box at the top of the screen -- not sure what others think about that.

**Comment by sjshores** [comment]
If I'm understanding things correctly, I think we need the start over link
because it takes you out of that category of materials (catalogue or
journals or databases) and brings you back to a page where you can search
across all types of resources, including EDS.  By contrast, the search
again box keeps you within the group of resources you had selected, such as
the catalogue.

I agree that start over should not generate random and massive search
results on the bento pane page.  Could it just go back to the main webpage
and the empty search box there?

Sandra

**Comment by seanluyk** [comment]
I agree with @linds37 and @sjshores , and I think I mentioned this in a comment elsewhere before. I think this is a pretty big usability issue - it gives users the impression that they've searched for something when they haven't.

**Comment by redlibrarian** [comment]
OK. I've changed the start-over link to take you back to the home page. "Back to search" will continue to take you back to your search button.

**Comment by linds37** [comment]
Should this be working in the current release? I'm still seeing the randomly generated list of results.
