### ISSUE TITLE
Kanopy video records

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#706]
Reported by Emily Z:

Firstly, a lot of Kanopy records that exist in Sirsi are not showing up in the "Books, media, and more" bento box at all. They do appear in the EDS box, but are labelled "eBook." 

For example, EDS result 1) is the Kanopy record, result 2)  is a physical copy from MacEwan.
![image](https://cloud.githubusercontent.com/assets/14880206/11077853/58b65ee6-87bf-11e5-8dbf-869fddd95ba0.png)

Some Kanopy records do appear in the right bento box, like this:
![image](https://cloud.githubusercontent.com/assets/14880206/11077856/5f27d732-87bf-11e5-8143-672f8d619984.png)

But if I click into the record, it's really difficult to get to the actual video! 2/3 of the links do not work at all, and the one that does is buried:
![image](https://cloud.githubusercontent.com/assets/14880206/11077862/6798d416-87bf-11e5-98e6-07d2e1f3865d.png)

**Comment by seanluyk** [comment]
I think you can ignore the last part re: error message. I think this is the intended behaviour.

**Comment by sjshores** [comment]
I think the three different links are working correctly, but that usability
would be improved by moving the true link to the item up in the display
just under the title.

Users should not place holds for online materials, and the location link
correctly tells the person to click on the access button.  But if we moved
the link coming from the 856 up so that it sits just under the title, the
user would more likely be drawn to it immediately.

Sandra

**Comment by seanluyk** [comment]
@sjshores  - that's a really great idea, and ties in with the idea of direct linking to electronic resources that we discussed a couple of meetings back. An alternative may be to make the titles of electronic resources hyperlinked with the UofA access link, but I'm not sure if this possible, or if it creates issues when links change, etc.

**Comment by redlibrarian** [comment]
@sjshores I can move the link to make it more prominent. I'm not sure, however, whether I can easily suppress the Place Hold link depending on the information I get back from Web Services. I'll have to look at the WS response and check with you on what data/logic is necessary.

**Comment by sjshores** [comment]
As long as you can move the link up and give it prominence through colour,
etc. then the existing hold link is no problem.  I don't think users will
notice it when the URL is so visible.

Sandra

**Comment by redlibrarian** [comment]
OK, looks like the WS can return whether an item is holdable or not (and I just checked, it takes account of multiple items with different 'holdability'), so I can use that to suppress the Place Hold button.

**Comment by sjshores** [comment]
Even better.

Sandra

**Comment by redlibrarian** [comment]
All right, I've added the logic to suppress "Place Hold" if no items are holdable. That will be present in the next release. Moving the link is proving a little bit trickier, but I'll get there.

**Comment by redlibrarian** [comment]
I've repositioned the link for UA items so that it appears prominently right below the title. I've left non-UA links, along with their note, at the bottom of the screen, so that users don't click on the prominent link below the title and wonder why they don't get access. I'd like the @ualbertalib/discovery-testing to try this out in the next release and see if it fits the bill.

**Comment by redlibrarian** [comment]
@seanluyk @sjshores The UA link has been moved to just below the title. All other libraries' links are put lower on the screen. Let me know if this is acceptable.

**Comment by seanluyk** [comment]
Looks great - UofA access link is prominent, and the place hold button is not appearing. Closing issue
