### ISSUE TITLE
Possible issue - top navigation does not freeze in Bento and results views

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#710]
I noticed that the top navigation freezes on the main page when scrolling, but not on Bento or results view pages.

**Comment by nnunn** [comment]
I think this is the right action - making the navigation fixed on the results page would feel a bit strange as it would cover your results... on the home page it makes sense because of the one page design. I'm not totally sure though and we can make the navigation fixed (or frozen / stuck to the top) on results and bento. I think maybe we need a few more people to look at this / user testing?

**Comment by seanluyk** [comment]
Sounds good, @nnunn, this makes sense to me re: the results page. What do others think about the bento page?

**Comment by sjshores** [comment]
I think we choose either option, so maybe we should leave that issue to
usability testing.

Sandra

**Comment by redlibrarian** [comment]
No comments have come in about this this term. I'm going to close this. If usability or users report a problem we can look at it again.
