### ISSUE TITLE
Using "The" in basic search yields no results

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#716]
Not sure if this has been noticed already but was helping a student look up a few titles (and the majority worked like a charm!)  Except one was "The Undergrounders" - with my morning brain I typed in "The Undergrounders" and the Books Media and More pane tells us no resources were found but we did get hits in the EDS pane. This prompted me to realize I'd used "The" so I redid the search and got some results. Is this expected behavior?

The student was really surprised by all of this as she watched me search and she said "I would have assumed you don't have it."
I realize articles are stop words but our users are going to use them - and my worry is they won't see the book appearing in the EDS pane.

**Comment by merisjames** [comment]
This happened with "a" as well... Which makes "A Wind in the Door" a bit of a challenge to find, if someone does a quick cut and paste of the title.
I think this happened before (stop words stopping the whole search) but had been resolved. Something must have changed to make this happen again.

**Comment by seanluyk** [comment]
Oh no, this is the "The Catcher in the Rye" problem coming back! This seems to go back and forth between working and not working

**Comment by merisjames** [comment]
Heaven help you if you try to avoid this by searching "wind door l'engle" (no quotes). 19499112 hits. EDS seems to be treating the ' as a space, and throwing up everything with just "L" (initials, etc). At least until you try to "View all articles" at which point you get nothing.

Interestingly, "a wind in the door" works fine in phrase search.

**Comment by redlibrarian** [comment]
This actually shouldn't happen - and I don't think it was happening before. Something must have changed. Just FYI a lot of search engines are dropping stopwords so that **of mice and men** for example doesn't just do a search for **mice** and **men**. We still have stopwords turned on, so searchers for **undergrounders** and **the undergrounders** should bring back the same result set (containing both). I'll look into it.

**Comment by redlibrarian** [comment]
Sigh, this again. It turns out that the mm "fix" that I put in place a few months ago, was to fix this problem, and fixing the search/ranking by fixing the mm has brought this problem back again. The problem is that some of the fields used for the default search are not set to use stopwords, so solr can't figure out how to match on them when a stopword is present. Summary of the problem here: https://groups.google.com/forum/#!msg/blacklight-development/fsmZOIOgBBk/upXDxFRJtPIJ
and here: https://bibwild.wordpress.com/2010/04/14/solr-stop-wordsdismax-gotcha/

The solution seems to be, either stop using stopwords altogether, which some institutions have done, or make sure that all fields in your qf definitions are using the same stopword definitions.

**Comment by redlibrarian** [comment]
OK, so I tried various changes to the "qf" field in solrconfig.xml and found that there were two culprit fields, subject_topic_facet and id, both of which are defined as strings in schema.xml. **string** obviously ignores stopwords, so these fields were the problem. subject_topic_facet is copied into subject_topic_unstem_search, so it could easily just be removed from "qf". But id is needed to be able to search by record ID. I changed the definition in schema.xml to "text" (which handles stopwords), and this seems to work.

**Comment by redlibrarian** [comment]
Weird, this fix doesn't seem to have taken effect.

**Comment by hannepearce** [comment]
Yes this issue is resolved

**Comment by redlibrarian** [comment]
OK, thanks.
