### ISSUE TITLE
Bug - short results list in BMM provides no results link or box

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#723]
1. Searched for [Strange and Sacred Noise john luther adams](https://search.library.ualberta.ca/results?utf8=%3F&q=Strange+and+Sacred+Noise+john+luther+adams) in everything

Was expecting to see a link to number of results, and View all button. I wonder if there's a threshold where <X results these don't display?

![image](https://cloud.githubusercontent.com/assets/14880206/11160333/b38b77e4-8a25-11e5-894f-41f425c8b919.png)

**Comment by redlibrarian** [comment]
@seanluyk Yes, the box will display up to 15 results. If there are less than 15, it doesn't provide the link to the result list. The rationale was because you can see all the results, but since we present more metadata on the result list page, I can see changing this behaviour to always give you a link to the result list. @nnunn do you have any thoughts on this?

**Comment by sjshores** [comment]
Piping in, too, I like adding a link to all results even if the number is
15 or fewer, because of the additional information available and also for
consistency.

Sandra

**Comment by redlibrarian** [comment]
Thanks @sjshores I agree. @nnunn I can make that change. It will be ready in the next release.

**Comment by redlibrarian** [comment]
@seanluyk @sjshores @nnunn We have the same logic in place for all bento panes - I assume they should all have the same (new) behaviour?

**Comment by redlibrarian** [comment]
Didn't make it into today's release. Please check in the next one.

**Comment by redlibrarian** [comment]
@seanluyk This should be working now.

**Comment by seanluyk** [comment]
Fixed, closing
