### ISSUE TITLE
Combined print and electronic records problem with At Library/Online

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#744]
Something wonky is going on with the access facet:

1. Searched for Chinese opera cantonese
2. Selected books, media and more container
3. Limited to format = musical recording
4. Limited to access = at library

[Results](https://search.library.ualberta.ca/symphony?f%5Belectronic_tesim%5D%5B%5D=At+Library&f%5Bformat%5D%5B%5D=Musical+Recording&q=chinese+opera+cantonese) are a mix of physical and online musical recordings.

**Comment by redlibrarian** [comment]
Example record that shouldn't be appearing: https://search.library.ualberta.ca/catalog/5831000

**Comment by redlibrarian** [comment]
@seanluyk The example problematic record I found is because e.g. Olds College doesn't have a separate location for it's electronic items. This presents a problem for the logic. I'll have to discuss it with @theLinkResolver and @sjshores

**Comment by sjshores** [comment]
If you're using the library policy to determine this facet, that will not
be successful.  If you can use item type instead, you could select
Electronic Resources (E-RESOURCE) for the online facet and all else for "at
library".

Sandra

**Comment by redlibrarian** [comment]
Thanks @sjshores . This will require a bit of rethinking/rewriting code. Hopefully I can get this done tomorrow.

**Comment by seanluyk** [comment]
@redlibrarian I think it's ideal if this gets fixed before launch. What do others think?

From experience with supporting EDS from a public services perspective, I recall users having trouble with GetIt! dead ends, etc. This might result in similar confusion.

**Comment by sjshores** [comment]
I agree that this is an important one to fix before launch.  It's a great
feature to have in the new search service, and we'll want it to work
correctly.

Sandra

**Comment by redlibrarian** [comment]
@sjshores The item type is associated with an item record, correct? I'm not sure I have access to that data except through the Symphony WS, which is too late to index and create a facet. @theLinkResolver I assume there's a 008 or other fixed field that would give us this information, but how does that work currently with records that are a mix of print and electronic (I realize we're moving away from that model, but we still have combined records...)?

**Comment by sjshores** [comment]
Sam, you're right that the item type is part of the item record, so not
available for a facet.  Scott may have some advice based on the MARC record
itself.  One possible solution could be the present of the 856 tag to
indicate online access, as long as we could distinguish between links to
full text and links to contents notes, for example.

Sandra

**Comment by redlibrarian** [comment]
@sjshores - yes, the 856 was what I was originally using, but it had some disadvantages (though I can't think of what they are now). I'll investigate a little further.

**Comment by redlibrarian** [comment]
I've added a new BeanShell script in SolrMarc/index_scripts/eresource.bsh, which uses the presence of an 856. I can't see if it works because I don't have access to a large enough data set. I'll have to run it tomorrow on my workstation and see how it looks.

**Comment by redlibrarian** [comment]
Looks like it's partly working, but I'm getting some false positives like http://localhost:3000/catalog/366954 (no 856 at all). Same with http://localhost:3000/catalog/359529

Not sure what's going on - I'll look into it tomorrow.

**Comment by theLinkResolver** [comment]
The bottom line is that looking at the item records (home location=INTERNET or Item type=E-RESOURCE -- we would need to verify whatever is used most consistently throughout NEOS) would be the most precise way of dealing with this.

In the short term, looking for the presence of an 856 would be helpful, but the indicators would need to be considered, to filter out some of the things that aren't links to the resource. Here's a snippet from MARC:

![856](https://cloud.githubusercontent.com/assets/14913579/11405509/6e7dc014-9365-11e5-853f-f0ba09b64611.jpg)

What you are looking for in the second indicator position is a 0 or 1 ('resource' or 'version of resource'). However, that does not tell the whole story (and I confess I didn't realize this at first, because it's rare we link to TOC for serials)..

A table of contents would be considered to be a *constituent unit* of the resource (rather than a 'related' resource), and therefore the second indicator would still be 0 or 1. Only the text in the $3 would tell you that it is the table of contents. So you would need to filter certain text strings out. Maybe not so ideal.

Another field you could look at would be the 338 (carrier type). You would be looking for the text "online resource". There can be multiple 338 fields and you would need to look at all of them. But in searching for examples, I quickly lost confidence in that field. (e.g. 2726032, 2716480 - I don't know why there is a 338 describing the print characteristics; 2504755 - 338 says online but it's not).

Back to the 856, maybe it's simply the text "access" that you are looking for in $3, because that word should always be used after the library names ("MacEwan University Access" etc), but it typically does not appear in the 856s that are for table of contents or publisher's descriptions.

**Comment by sjshores** [comment]
Scott, I agree with your idea of looking for the word "access" in $3 in the
856.

Sandra

**Comment by redlibrarian** [comment]
OK thanks @sjshores @theLinkResolver - I think that's the best thing to go on right now, and is an easy change to the code I wrote last night to start looking at the 856 in general.

**Comment by redlibrarian** [comment]
OK, I think I have this working. It checked the value of the 856$3, and if it contains the word "Access", it's marked as Online. I'm unclear as to how this handles combined print and electronic records, though, which was something the old logic managed. We'll check this in the next release and go from there. / @sjshores @theLinkResolver

**Comment by sjshores** [comment]
I'm hoping that this will get us most of the way there.  As we continue to
separate electronic items from records intended to describe print, this
solution should become increasingly accurate.

Thanks,

Sandra

**Comment by redlibrarian** [comment]
@seanluyk Can you check this and see what you think? I think it looks like an improvement...

**Comment by seanluyk** [comment]
This appears to be working correctly now, closing issue

**Comment by theLinkResolver** [comment]
@redlibrarian I'm going to reopen this, because you were right to wonder about the logic around combined print+online records. Here's an example:

https://search.library.ualberta.ca/symphony?per_page=100&q=journal+economic+perspectives

From this result set, I am interested in the first title. It has Red Deer internet access plus print holdings for some other libraries. When I click "At Library", this result disappears, but we don't want it to.

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver - in the old logic, the system handled combined print and electronic. I can probably fix this, but the final separation of print and electronic records should fix the problem for us. If this will take place before April, then we probably don't need to fix anything. If it will take longer than that, then I'll look into reconciling this logic. / @sjshores

**Comment by seanluyk** [comment]
For this particular example, it seems to be working as expected like before. It's worth testing this one a little more I think.

**Comment by redlibrarian** [comment]
I'm going to move this to v.2.0.0 - this doesn't seem to be working perfectly, but I need to get a handle on the timeline for complete separation of print and electronic.

**Comment by redlibrarian** [comment]
I haven't heard any problems this term. Closable?

**Comment by seanluyk** [comment]
I just did a quick test on this, and I'm not seeing the issue I was seeing before. I think that it's safe to close.
