### ISSUE TITLE
Chat with us link on results screen

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#754]
Hi. PSC was asking about the Chat with Us link on the results screen. Chat is only available during the hours the library is open, so it shouldn't be there all the time. If it can't be scripted to the library hours, then it should link to the Ask Us page.

**Comment by redlibrarian** [comment]
@linds37 @gooyers brought this up after, I think, the last PSC meeting. If we make the current Chat box a link to the Ask Us page, then IMO we might as well remove it, since we already have a link to the ask us page in the top banner, and having two different links go to the same thing is redundant and potentially confusing. I've assigned this to @kgood though, for his take.

**Comment by linds37** [comment]
@gooyers  @redlibrarian Ok. Brian and I will ask PSC if they'd rather the link not be there, or leave it the way it is.

**Comment by gooyers** [comment]
@redlibrarian, @kgood, @linds37 
Lindsay raised this question at PSC yesterday and PSC made a recommendation on this. 

That the "Questions about your results or your research? CHAT WITH US!" link be changed to: Questions about your results or your research? ASK US! (with ASK US! being the same style of Blue button currently being used for CHAT WITH US!). With the button linking to the Ask Us page rather than the chat widget. 

Reasoning:
- During hours where chat is not being staffed, linking to the chat will lead to a page that is not useful. 
- Redundancy is a valid concern, but perhaps not around launch where multiple avenues of contacting us might be appreciated. Simplification/removal of the button could be considered post launch.
- While the Ask Us icon is present on every page (which is important), the "Questions about your results or your research?" language specifically alerts users that there is somewhere to click if they have a problem with this specific page/tool.

**Comment by redlibrarian** [comment]
@kgood Unless you have concerns around this, I'll make this change right away.

**Comment by redlibrarian** [comment]
Done. Check in next release.

**Comment by redlibrarian** [comment]
@linds37 This is live now.

**Comment by linds37** [comment]
Hi. Can you please change it to say "Ask Us" instead of "Chat with Us" on the link?
Thanks for changing the link destination.

**Comment by redlibrarian** [comment]
Yes, but it won't be visible until we go live in January, most likely.

**Comment by linds37** [comment]
ok. Thanks!
