### ISSUE TITLE
Journals results list - numbering and duplicate records

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#761]
For the [results for Fontes artis musicae](https://search.library.ualberta.ca/ejournals?q=Fontes%20artis%20musicae) from the journals container, I noticed a couple of issues:

1. There are three records listed, yet the access facet only shows that there are two, so one of the records is not being counted for some reason

2. It looks like we've got two records for the electronic access, and I'm not sure if this was intended. 1 record links to the GetIt! screen, and the other reproduces this information.

**Comment by redlibrarian** [comment]
Thanks @seanluyk - I'm not sure why the record count is off. I'll have to look into that. As for the duplication of records, this is a known consequence of having the e-journal records in two places. It will be fixed in Blacklight but not before January.

**Comment by theLinkResolver** [comment]
@redlibrarian I think the count problem has to do with the fact there is not an 856 in the SFX record, and therefore the text "Access" is not present, to get the Online facet. Then again, why is it not At Library? Does that have something to do with the SFX record not having item records?

**Comment by redlibrarian** [comment]
Huh. @seanluyk @theLinkResolver No, something else seems to be preventing the SFX records from having the At Library/Online data. They should all be Online, whether or not they have an 856, as all SFX journals are e-journals (no?). I'll investigate the underlying problem.

**Comment by redlibrarian** [comment]
OK, I figured this out. This will be fixed in the next release.

**Comment by seanluyk** [comment]
I'm only seeing 1 record for print, 1 for electronic for this journal, so I think it's working properly. Faceting at library or online returns the appropriate record. Closing issue.

**Comment by seanluyk** [comment]
This issue seems to have returned. For the [Fontes example](https://www.library.ualberta.ca/journals?utf8=%3F&q=Fontes+artis+musicae), there are again three records, one of which does not have a UofA Access link (just links to various providers)

**Comment by redlibrarian** [comment]
This is likely due to a *different* underlying problem. The Journal facet contains print and electronic records from Symphony as well as SFX records (originally, the Journal facet only contained SFX records). Earlier, print and electronic records were combined into a single record and now they have been split. This results in three separate records. I am working on figuring out how to deduplicate the electronic records, but - fair warning - now that we split the print and electronic records in Symphony, we will *always* have duplicate Blacklight records when we have both print and electronic holdings. This is a bib services/cataloguing, not a discovery piece.

**Comment by seanluyk** [comment]
Thanks, @redlibrarian - feel free to close this issue since it's a bib services piece. 

I guess I'm still wondering what the advantage is of having both SFX and electronic journal records appearing in the system. I like how clearly the SFX record displays access/rights info, but I guess we lose subject headings in the process.

**Comment by redlibrarian** [comment]
@seanluyk I'll leave it open, since it needs to be dealt with. I think I've figured out a good solution for the SFX/symphony e-journal records. The Symphony records are richer than the SFX records, but all we're using the SFX records for is to get the individual subscription/rights information. Instead of deduplicating the records, I think the best solution is just to supplement the Symphony records with the SFX information, without using separate SFX records, if that makes sense. This will eliminate duplication between SFX and Symphony, and give us rich records (e.g. subject headings) AND the access/rights information. / @theLinkResolver @sjshores I just thought of this solution this afternoon, I'll run it by you next week.

**Comment by sjshores** [comment]
My concern with this approach is that we have activated many more records
in SFX than we have catalogued in Symphony.  One of the advantages of the
original plan to use SFX for serials data was to increase the number of
records available to users.

Sandra

**Comment by redlibrarian** [comment]
@sjshores Are those additional records strictly speaking Journals? Or are they the records for other kinds of serials? We'll be able to import those (I don't think we're currently doing that but @theLinkResolver seems to think some of them are coming through).

**Comment by sjshores** [comment]
The records are for journals, and it's really good to be able to include
them.  They greatly expand what we don't want to include in our normal
cataloguing procedures due to the time/expense it can take to catalogue
journals (e.g. less scholarly titles from large packages), and to our
policy of not cataloguing free items for example.

Sandra

**Comment by seanluyk** [comment]
I think this one can be closed for now, as the issue doesn't apply anymore.
