### ISSUE TITLE
028 $b (and others?) need to be displayed

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#796]
Just a minor, mostly music related one that I noticed. It doesn't look like the 028 subfields (mostly concerned about $b) are being displayed in the publisher / issue# field (which displays in iLink as other music #). 

Not a showstoper of course, but these are necessary because sometimes the publisher is different than the distributor, and what's recorded in the 260 doesn't always match 028 $b exactly, but correct me if I'm wrong @theLinkResolver

These are really messy and variable fields, and it may be worth looking at them more closely at a later date. The main use case for getting this right is for verifying you're using the same score, or recording as you think you are, and for citation purposes.

**Comment by theLinkResolver** [comment]
@seanluyk Wow, you got me - I'm not familiar with this field, but that's because I specialize in serials. It's nice to learn a bit about this field. From looking at the rules around this field, your presumption seems to be correct. 

@redlibrarian This field contains three subfields of interest (a - publisher number, b - source of publisher number [record label or publisher's name], and q - qualifying info [e.g. explaining to which part, disc etc. the number belongs]). The upshot is that the contents of the field need to stick together, which I know can be tricky. The good news is that it looks like the subfields always appear in this order (a, b, q). The field name in iLink varies based on the indicators (could be issue number, plate number, other music number, etc.); the catch-all field name would be something like "Publisher number" or "Publisher's number". Hope that helps.

**Comment by seanluyk** [comment]
Thanks, @theLinkResolver, this is a very helpful clarification. @redlibrarian please file under "rainy day catalogue related enhancement", as this is not crucial

**Comment by redlibrarian** [comment]
OK, I've added $b and $q to "Publisher Number". For example, in record 1000055 the Publisher Number now appears as: NKF 30058 Norsk kulturråds klassikerserie (in production it currently reads only "NKF 30058"). I'll let you know when this is in test and you can see if that is satisfactory.

**Comment by seanluyk** [comment]
This field is displaying in full, looks good
