### ISSUE TITLE
Make authorship more clear

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#827]
I've been thinking that there may be a better way to deal with authorship in Blacklight (applies especially to works with multiple contributors, but also with single author works too).

Here is one example: https://search.library.ualberta.ca/catalog/3836242
See the [iLINK record](http://www.library.ualberta.ca/permalink/opac/3836242/WUAARCHIVE) for comparison.

The editor (Cowdery, James R) is mixed in with various other contributors (with their roles stripped away) who have much more minimal roles in the work (e.g. writing the foreward, introduction, etc.). The 710 is also bunched in there, but it doesn't really fit in this case I don't think (they aren't an "author"). The way this field reads, it implies that each of these contributors are equal, when they aren't. I'm thinking about how a student may cite this work too. 

It may be better to eliminate this extra info - is it really essential? The alternative would be to work towards separating it out in a more meaningful way. For example, putting the editor in the author field, and putting everything else in the additional contributors field or something.

What does everyone think?

**Comment by merisjames** [comment]
I think author(s) + additional contributors would work. 

It seems to work quite well for the many law texts with multiple/changing authors, such as https://search.library.ualberta.ca/catalog/3532439 (although strictly speaking, La Forest should be the author, as Anger has been dead over 60 yrs) or https://search.library.ualberta.ca/catalog/2583434 or https://search.library.ualberta.ca/catalog/2136521 (Choate is long gone, so Cudmore is correctly noted as the author, and Choate as the "additional").

**Comment by theLinkResolver** [comment]
From the data/cataloguing side, I can also point out that most, but not all, author information is part of the record display. The two pieces of the puzzle that are missing are:

1. Statement of responsibility information (for those used to thinking about MARC records, this is the text appearing after the slash (in $c) in the 245 field).
---The information here is quite important, and addresses some of the concerns raised above. Basically, what gets transcribed here is prominent information from the title page that describes persons/bodies responsible for the content of the item, sometimes including words that describe their function (e.g. editor, illustrator, etc.). This is how it is presented in iLink:

![ilink sor](https://cloud.githubusercontent.com/assets/14913579/11903792/d6024690-a578-11e5-8410-29fb4228afcb.jpg)

Here's an example from another Blacklight system of how it's been handled (see "responsibility" field):

https://searchworks.stanford.edu/view/7105806

I am personally of the belief that we should be presenting this information in Blacklight records, and with some prominence, as the intent of the field is to capture what the publisher presents on the title page, to aid in identification. The words, such as "with introduction by" etc. help to justify/explain the added author entries such as the ones Sean describes above. They can also tell you something about the work itself, like this:

![ilink eg 2](https://cloud.githubusercontent.com/assets/14913579/11903930/f8a216a2-a579-11e5-94a2-9994e4d52fbe.jpg)

I should note, in this example, there is nothing in the 700 fields that clarify the roles/functions of those named. Only the statement of responsibility does this, so there would not be a way to safely keep one and exclude the others. (I see the Stanford record only displays Cowdery and the organization as added authors - this is because it looks like their record did not include the other added entries in the first place. "Cataloguer's judgement"!)

2. Added entry - uncontrolled name (720 field).
---I'll spare you all the explanation, but this info should be indexed for search purposes, as it is another point of authorship that is recorded, albeit in very limited circumstances. In iLink, we do not actually display this field, but it is searchable. In consultation with Brian Stearns, this is an acceptable treatment for Blacklight, as well (searchable, not displayed). In the grand scheme, it would be a lower priority to deal with this particular piece of data.

**Comment by redlibrarian** [comment]
What we're going to do for now is turn on the additional title display and place it close to the additional authors. I'll also add the additional authors to the "more by this author" block. In order for this to work, add $d to the addl_author_t field. As a later project, we'll look at constructing a proper uniform title that can be used as a facet.

**Comment by seanluyk** [comment]
A wacky example of additional authors that could serve as a good test case: https://www.library.ualberta.ca/catalog/6458885

**Comment by redlibrarian** [comment]
Additional titles have been turned on, and additional authors are now clickable/searchable. I suppose all that's missing right now is the "role" ($d).

**Comment by redlibrarian** [comment]
OK. The $d is now in place and the role is listed next to each additional author. This *may* cause unintended consquences when searching, but we'll have to see how that works with a full index.
