### ISSUE TITLE
Multiple U of A 856 links

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#838]
This record: https://search.library.ualberta.ca/catalog/815666

has multiple 856 links. The good news is that all the links are presented as per the existing logic. The bad news is I think is is pretty ugly and not user-friendly. @theLinkResolver @sjshores Is this proper cataloguing procedure (I assume so)? We should discuss in the new year what we want to do to make records like this easier to use.

**Comment by redlibrarian** [comment]
Weirdly, I don't see any "internet" items for U of A (just Red Deer)...

**Comment by theLinkResolver** [comment]
This is a notorious record in these circles... There are a couple of things at play here. The record cited above has had the UA internet holdings moved to an e-record. I've now arranged for the RDC holdings to be relocated to the e-record, so let's point to that one for the rest of the discussion:

https://search.library.ualberta.ca/catalog/6845417

The cataloguing treatment of these links is generally correct. The preferred link for a gov pub is a DSP or LAC version (2000/2001- here), but because the departmental website has earlier access (1996/1997-), we put that in there, too.

There is a problem with three of these. Three of the links are for the supplementary estimates sections, which have separate URLs. The 856 $3 is not quite formed properly, and so BL is not showing us all the $3 text -- 

incorrect: Free Access. Supplementary Estimates (A): 1996/1997-
correct: Free Access: Supplementary Estimates (A) 1996/1997-

@redlibrarian It's a cataloguing problem, but one we might have to deal with. I actually have lots of examples from another project where the colon is missing from the 856 $3, or another character (such as a period or comma) follows the word "access". Depending on what your display logic is doing to clean these up for display, these might not be getting displayed correctly. Not trying to pass the buck, but the logic might need to take this into account in the context of our huge database and consortial realities... :)

**Comment by redlibrarian** [comment]
@theLinkResolver OK, fair enough. Thanks for the explanation. Let's talk about it more in the new term.

**Comment by redlibrarian** [comment]
@theLinkResolver This record looks like all-print now. Does it look OK to you?

**Comment by theLinkResolver** [comment]
@redlibrarian Yes, let's just close this. Re. multiple links, we want them all displayed. They are what they are, and they're informed by various policies, needs, etc.
