### ISSUE TITLE
Call number search working?

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#854]
When I search for KF 2925 S27 2011 I get [2 results] (https://www.library.ualberta.ca/results?q=KF+2925+S27+2011). The first one is the right book, wrong year, the second is just the wrong book. The same search in NEOS brings up [the correct record] (http://www.library.ualberta.ca/permalink/opac/4844347/WUAARCHIVE), so it's there, just not coming up in my search.

**Comment by merisjames** [comment]
I wonder if that has something to do with getting a "something went wrong" when trying to view the actual book you want... https://www.library.ualberta.ca/catalog/4844347 Something funky with the record?

**Comment by fculpepper** [comment]
Oh drat. No that was me trying to link to my search, I assumed the address
bar would permalink to it. I just searched the call #, kf 2925 s27 2011, in
the main search and got the two results.

**Comment by merisjames** [comment]
No, not at all, your link was fine! I followed it, then looked at other books by the author. The dead link is the one for the 2011 book, which I assume is the one you were expected to see in your results?

**Comment by fculpepper** [comment]
Oh gotcha! Yep, we were looking for the 2011 edition. So not a call number
search issue but a no-show item issue. Thanks!

**Comment by theLinkResolver** [comment]
Re. the two results you do get, I wonder if these are coming back because most of the search terms (i.e. bits of the call number) match. (Which suggests, in this relevance-based system, that using quotes around call numbers might be a necessary step when looking up a known call number.)

However, the non-retrieval is concerning. The search should also retrieve this record - https://www.library.ualberta.ca/catalog/3973940 (again, matching on most bits of the call number). In this case, I'm wondering if only the first 090 (call number) field is part of the search index. (see also #846)

As to why https://www.library.ualberta.ca/catalog/4844347 doesn't load, I don't see anything on the cataloguing end. Hoping @redlibrarian can figure that one out.

**Comment by theLinkResolver** [comment]
for 3973940, the first-listed call number (090) field in the record is for C-FER, just to clarify what the heck I'm talking about in my previous comment. 

As is the case in the Classic Catalogue, keyword searching for a call number is looking at the call numbers listed in the bib record, rather than the call numbers in the items. Hence the need to make sure all the 090 fields are indexed, as there can be quite a few among us and our NEOS pals.

**Comment by redlibrarian** [comment]
@theLinkResolver Are the 090 call numbers correct? I thought one of the reasons we don't use them for display is that they could differ from what we actually have on the items. It should be possible to index all the 090s (Blacklight is probably assuming only 1 per record), but if it would be better to index the *item* call numbers, then we'll need to discuss that (as we currently don't index item level data).

**Comment by theLinkResolver** [comment]
@redlibrarian Good to clarify. The 090s do match the items. It's the 050s that don't, but are used for the call number facet.

**Comment by redlibrarian** [comment]
@theLinkResolver OK, thanks - that's great. I should be able to index multiple 090s pretty easily.

**Comment by fculpepper** [comment]
Just to clarify, if the record does not have an 050 searching the call number won't retrieve it? A coworker just brought a non-retrieving call number to me (HC 79 E5 G373 2011) and I want to make sure I give her the right answer :)

**Comment by redlibrarian** [comment]
@fculpepper That's currently true. When I've indexed the 090s, there should, I think, be better coverage. @theLinkResolver is that fair to say?

**Comment by theLinkResolver** [comment]
@redlibrarian @fculpepper That's correct.

**Comment by redlibrarian** [comment]
This is done (see #846 ). Please test in next release.

**Comment by theLinkResolver** [comment]
Tested here and with issue #846. Working great. 

@ualbertalib/discovery-testing @ualbertalib/serials-cataloguing An important takeaway here is that you will want to put quotes around the call number to increase precision (and to replicate the experience you are used to with the old system). 

Then again, you may discover another edition or closely related work if you don't use the quotes, which might not be a bad thing (and the perfect match seems to always be the first hit in my tests).

@linds37 I see you have covered call number searches in the search guide. Looks good - and, in light of the above, you might consider adding a note about using quotes to find _only_ that call number.

**Comment by linds37** [comment]
thanks - done!!
