### ISSUE TITLE
items purchased through the textbook initiative (reserve) - publication year not displaying

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#855]
Searching for Financial accounting: tools for business decision-making 2013 edition

https://www.library.ualberta.ca/symphony?q=Financial%20accounting:%20tools%20for%20business%20decision-making

it is actually the 4th item in the list but not immediately apparent as the publication year doesn't display. Limiting by publication year doesn't work as the system can't find the data. 

Another example 

Intermediate accounting (HF 5635 K45 2013 - kieso, ... ) -  https://www.library.ualberta.ca/catalog?q=intermediate+accounting+kieso - number 16 on this list;
number 12 on the list if you further limit by author (kieso) - https://www.library.ualberta.ca/catalog/6704086 
Record isn't in the list of search results when you search for the call number without the year - https://www.library.ualberta.ca/symphony?q=%22HF+5635+K45%22

**Comment by merisjames** [comment]
This is the same issue we had during training yesterday, I think... Items we were expecting were not coming up when limiting or sorting by year, because there was "no year" on the record. I don't think we had a solution at the time, but this is starting to seem like a larger issue than just the one search we were playing with.

**Comment by theLinkResolver** [comment]
@redlibrarian The first problem above is because this is an RDA record with the pub date in the 264 field. same as issue #746. 

And to echo @merisjames, we are starting to see how "no year" manifests when sorting..

The second problem is because all the 090s need to be indexed - the U of A call number is the second one in the record. same as issue #854

**Comment by redlibrarian** [comment]
OK. well we'll see how this one shakes out when we've indexed all the call numbers and the dates from 264.

**Comment by redlibrarian** [comment]
... which I don't think we've done yet.

**Comment by theLinkResolver** [comment]
Fixed in test.
