### ISSUE TITLE
Publication Year Filter

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#871]
Publication year filter: the displayed years change when you interact with it.
Initial options were 1997 - 2014: Interacting with slider etc changed these to 1998 - 2015

**Comment by redlibrarian** [comment]
@merisjames Any interaction? Or a specific interaction?

**Comment by merisjames** [comment]
It's done it every time I've demoed the feature in training. It isn't
always both the high and low end that change... Sometimes it's only one.
But...
Search for metis, enter books and more.
Starting age range: 1870-2014
Click on "bottom" blue slider: 1872-2015
Refresh.
Click on "top" blue slider: 1870-2015

Meris James, MLIS
Public Service Librarian
J.A. Weir Memorial Law Library
meris@ualberta.ca

**Comment by redlibrarian** [comment]
OK, thanks. I'll look into it.

**Comment by redlibrarian** [comment]
Weird. The bottom slider seems to be sensitive to the position of the cursor, so I think that one's moving "up" as expected. I don't know why the top date should be affected. I'll look into this, but I don't think this is critical enough that it *necessarily* needs to be fixed by May launch. I might put this into a different milestone if it's tricky to fix.

**Comment by redlibrarian** [comment]
We're up-to-date with the gem. I'm going to move this to look into over the summer.
