### ISSUE TITLE
Database Subject Terms

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#875]
The high number of subject terms that have been assigned to some of the databases in Libguides is causing false hits. Should they mirror the subject terms that are assigned in catalogue records? Needs to be a focussed discussion/analysis on how everything is working with the new approach to databases.

**Comment by redlibrarian** [comment]
@merisjames This is a question primarily for public services librarians/staff who are responsible for databases. However, I'm not sure that this has been communicated to public services staff particularly. @sjshores @linds37 thoughts?

**Comment by linds37** [comment]
I agree with Meris that it's an issue. Is this something that can be looked at by a cataloguer?

**Comment by redlibrarian** [comment]
My understanding was that since databases were now being managed within LibGuides, initial subject assignment would be done by acquisitions, and more precise subjects would be assigned by subject librarians. @sjshores this came out of the database meetings we had with Denise, Ernie, Angie, and a few others, as far as I remember.

**Comment by sjshores** [comment]
Yes, during the meetings we have had to date about new processes around
dbs, Angie expressed that public services staff should add subject keywords
to the databases in LibGuides and that BL would use those for indexing and
searching.  The thinking was that PS staff have a good sense as to how
users think about the databases and how staff want to highlight them in
LibGuides.  This process would also mean that there is consistency in how a
database is described in LibGuides and how it is found through search.

Lindsay, if this is not the right approach, can you please have a
discussion about it with PSC colleagues?  We can always bring in LCSHs, but
now's the time to let us know as we're re-examining all processes related
to databases, including whether or not we should continue to catalogue them
in Symphony.

Thanks,

Sandra

**Comment by linds37** [comment]
Hi, Sandra. I don't know whether some of the databases have such a high
number of subject keywords assigned because individual subject librarians
are all adding terms, or if one person is adding too many. Were any added
by April when she entered them all into Libguides?
It seems there needs to be a limit to the number of terms, though I don't
know how librarians coming from different disciplines will agree on what
they should be. The solution that automatically comes to mind is a
controlled vocabulary. I don't know how many databases have long lists of
terms, so I'm not sure if this is a widespread issue or only applies to
specific cases. Is there a way to run a report?
I can certainly discuss with Angie (since she has the background on the
decision) and we can decide whether to bring this to PSC.

Thanks,
Lindsay

**Comment by sjshores** [comment]
April, are you able to produce a report from Libguides as per Lindsay's
note below?

Thanks,

Sandra

**Comment by seanluyk** [comment]
I think it would be a good idea to look at how subject associations are being added, and for a policy to be developed. Should each database get its 1 best subject assigned to it, or is it better to have more? For truly multidisciplinary databases, should a multidisciplinary label be applied?

For example, one of the music databases (Rock's Backpages), which is essentially an archive of key popular music articles from magazines, has been classified (not by me) as: Art History, Arts, Music, Musique. It really has little to do with art history, or arts more generally, but someone thought it did, probably because the content could be argued to intersect with these areas.

**Comment by linds37** [comment]
Hi. Just another issue -- users have been noticing that when they use the
alphabetical listing on the databases list, titles that start with The or
Le are listed under T <http://guides.library.ualberta.ca/az.php?a=t> or L
<http://guides.library.ualberta.ca/az.php?a=l> instead of the first letter
of the more meaningful word in the database name. Staff tend to look up by
the name of the database, but users seem to like to use the alphabetical
listing, in case they can't remember the exact name of the database, etc.
Is it possible to skip the article or leave it out?

Lindsay Johnston, Public Services Manager & Subject Librarian
Rutherford Humanities & Social Sciences Library
<http://guides.library.ualberta.ca/rutherford> and Weir Law Library
<http://guides.library.ualberta.ca/law>
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta
T6G 2J8
780.492.0598

lindsay.johnston@ualberta.ca

**Comment by redlibrarian** [comment]
@linds37 That's an issue with libguides, not with the discovery system. It's either a technical question (i.e. Springshare could make the list ignore leading stopwords) or a policy question, and I'm not sure who deals with those. / @sjshores

**Comment by redlibrarian** [comment]
@seanluyk To me, that's a question for public service/subject librarians and/or PSC. I could make a recommendation based on findability, but fundamentally it seems connected to the "aboutness" of the database, which IMO should be up to the subject librarian.

**Comment by alfodor** [comment]
The database subject list that was in the old system was imported into LibGuides. Since then, users have requested additions and deletions (see list). Initially we asked that subject librarians associate databases with subject areas but since many had no associations and weren't showing up in a LibGuides and Blacklight search in early December Sam C. took the information from the database of databases (attached) and did his best to make the same associations in LibGuides.

[subjects and associated databases.pdf](https://github.com/ualbertalib/discovery/files/101252/subjects.and.associated.databases.pdf)
[databases and associated subjects.pdf](https://github.com/ualbertalib/discovery/files/101254/databases.and.associated.subjects.pdf)
[subject list comparison.pdf](https://github.com/ualbertalib/discovery/files/101247/subject.list.comparison.pdf)

**Comment by redlibrarian** [comment]
The whole database question is about to be discussed/figured out. I think the current specific issues are all dealt with - I'd propose closing this issue and opening a new one if problems arise.
