### ISSUE TITLE
[Discovery] some URLs don't display

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#877]
Some URLs (based on the 856 field indicators, I believe) do not display. Special Collections noted that this means that the links to finding aids are not displaying the record, for example:

https://www.library.ualberta.ca/catalog/6282297
http://www.library.ualberta.ca/permalink/opac/6282297/WUAARCHIVE

856 indicators are 42, with the 2 meaning "related resource" (i.e. a link that is not for _the_ resource itself).

This coding is also used for links to supplementary materials, publisher's descriptions, etc.

Done when:
- [ ] Finding aid links displaying in the records

**Comment by redlibrarian** [comment]
@theLinkResolver Blacklight doesn't look at the indicators, so the presence of a label and url should be sufficient. The XML in a record that does display the link properly is the same as the XML in this record:

    <MarcEntryInfo>
    <label>Electronic access</label>
    <entryID>856</entryID>
    <indicators>40</indicators>
    <text>University of Alberta Access: 1985-</text>
    <unformattedText>
    |3University of Alberta Access: 1985- |uhttp://resolver.library.ualberta.ca/resolver?    ctx_enc=info%3Aofi%2Fenc%3AUTF-8&ctx_ver=Z39.88-    2004&rfr_id=info%3Asid%2Fualberta.ca%3Aopac&rft.genre=journal&rft.object_id=954925545272&rft.i    ssn=0820-3946&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004
    </unformattedText>
    <entryTypeCodes>iL</entryTypeCodes>
    <url>
    http://resolver.library.ualberta.ca/resolver?ctx_enc=info%3Aofi%2Fenc%3AUTF-8&ctx_ver=Z39.88-2004&rfr_id=info%3Asid%2Fualberta.ca%3Aopac&rft.genre=journal&rft.object_id=954925545272&rft.issn=0820-3946&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004
    </url>
    </MarcEntryInfo>

    <MarcEntryInfo>
    <label>Electronic access</label>
    <entryID>856</entryID>
    <indicators>42</indicators>
    <text>Finding aid</text>
    <unformattedText>
    |3Finding aid|uhttps://discoverarchives.library.ualberta.ca/index.php/clennell-punch-dickins-archive
    </unformattedText>
    <entryTypeCodes>iL</entryTypeCodes>
    <url>
    https://discoverarchives.library.ualberta.ca/index.php/clennell-punch-dickins-archive
    </url>
    </MarcEntryInfo>

What I'm wondering is whether this record isn't being recognized as "electronic".

**Comment by redlibrarian** [comment]
Found it. In SolrMarc, the indexer looks at the indicator to see whether the item has a URL 

"if the second indicator is 0, each subfield u is added to the Solr document. if the second indicator is 2, no value is added to the Solr document. otherwise, subfields 3 and z are examined. If none of the following text is present, then subfield u is added to the Solr document" (https://code.google.com/p/solrmarc/wiki/CustomIndexingRoutines)

However. I don't use this to construct the links, I only use this to tell whether an item *has* a URL. I should be able to work around this limitation.

**Comment by theLinkResolver** [comment]
@redlibrarian Good sleuthing and hope you can work around it.. 

I think we agreed that these kinds of links should *not* be recognized as electronic/online, as they don't have the word "access" - they're not links to the actual resource itself.

**Comment by redlibrarian** [comment]
Ok, I chatted with @theLinkResolver - I have a basic fix which I could put in place, but it would require adding handling for all 856|3 language in Symphony, which is only more-or-less controlled. I recommend that we put this question aside until we can take a step back and think more about how we want to treat "print material with associated URLs". I recognize that we want to promote and improve access to Special Collections material, but I'd rather get this right the first time than spend a lot of time tweaking after the fact. @sjshores does that sound OK? Also, I assume these finding aids are candidates for AtoM, but I doubt this will change the situation much, if at all.

**Comment by sfarnel** [comment]
This is one of the ones that was moved into AtoM from Libguides, as will all the others that are in HTML over time.

**Comment by theLinkResolver** [comment]
@redlibrarian maybe I'm missing a detail, but would adding the text "Free Access" to these finding aid links be an immediate/short-term fix?

**Comment by redlibrarian** [comment]
@theLinkResolver Sorry it took so long to get back to you. I don't think that will do it, because the indicator "42" just tells SolrMarc to skip the 856 tag altogether... this should come back for discussion in the summer.

**Comment by theLinkResolver** [comment]
For the record, I'm a bit uneasy about the finding aid links not being displayed at this time. Less so about the TOCs, publisher's descriptions, etc., which are also affected by this problem. 

Perhaps this issue could be an agenda item for our next meeting. We could probably ask Jim for a report of what else has 856 field 2nd indicator=2, to get a sense of the scope of "print material with associated URLs".

**Comment by redlibrarian** [comment]
Done when:

- [ ] Finding aid links displaying in the records

**Comment by weiweishi** [comment]
To display 856 field "Finding aid: https://discoverarchives.library.ualberta.ca/index.php/clennell-punch-dickins-fonds" on the record view. 
Data is available in solr:
https://www.library.ualberta.ca/catalog/6282297/librarian_view

**Comment by pbinkley** [comment]
@weiweishi to confirm: when you say "Position: under "title"", do you mean on the item display https://www.library.ualberta.ca/catalog/6282297 it should appear under the large title, like links to NEOS holdings do, with the same styling?

**Comment by theLinkResolver** [comment]
856 42s can do other things, such as providing publisher's descriptions and cover art (although we tend to get rid of these locally wherever possible). So there is also a decision about where 856 42s appear relative to other 856s. [example](https://www.library.ualberta.ca/catalog/6803667)

**Comment by seanluyk** [comment]
Requirements:

- Label "Finding Aid"
 - Placement - same spot as other electronic access (856) links
- Dealing specifically with 856 4 2 with URLs

**Comment by pgwillia** [comment]
Here's what I've found so far.

The values needed are indexed
```
#config/SorlMarc/symphony_index.properties
...
# URL Fields
url_fulltext_display = custom, getFullTextUrls
url_suppl_display = custom, getSupplUrls
...
summary_holdings_tesim = 8563
...
```
Found definitions for the URL Fields from https://github.com/solrmarc/solrmarc/wiki/Predefined-Custom-Methods

>getFullTextUrls:

>> gets the URLs for the full text of a resource described by the MARC record. For each MARC 856 field, if the second indicator is 0, each subfield u is added to the Solr document. if the second indicator is 2, no value is added to the Solr document. otherwise, subfields 3 and z are examined. If none of the following text is present, then subfield u is added to the Solr document * abstract * description * sample text * table of contents `url_fulltext = custom, getFullTextUrls`

> getSupplUrls:

>> gets the URLs for the full text of a resource described by the MARC record. For each MARC 856 field, if the second indicator is 0, no value is added to the Solr document. if the second indicator is 2, each subfield u is added to the Solr document. otherwise, subfields 3 and z are examined. If any of the following text is present, then subfield u is added to the Solr document * abstract * description * sample text * table of contents
>>> `url_suppl = custom, getSupplUrls`

The button is created using javascript?! https://github.com/ualbertalib/discovery/blob/master/app/views/catalog/_main_url_display.html.erb

It uses the label stored in Solr but gets the links from [SymphonyService](https://github.com/ualbertalib/discovery/blob/master/app/services/symphony_service.rb#L14-L23) via [HoldingsHelper](https://github.com/ualbertalib/discovery/blob/master/app/helpers/holdings_helper.rb#L8-L17) via [CatalogController](https://github.com/ualbertalib/discovery/blob/master/app/controllers/catalog_controller.rb#L37) 

Looking at the Solr data: http://solrcloud-test.library.ualberta.ca:8080/solr/discovery-test-2018-09-12/select?fl=id,summary_holdings_tesim,url_fulltext_display,url_suppl_display,source&indent=on&q=summary_holdings_tesim:%22Finding%20Aid%22&qt=standard&rows=100&wt=json
I can see that there are 49 records with "Finding Aid" somewhere in 8563.  Mostly there is a url_suppl_display (856 4 2 with URLs ($u)) but sometimes (5/49) there is a url_fulltext_display (856 4 0 with URLs ($u)).

Mostly they are "Finding [Aa]id" (35), but also 
- (6) Free Access: Finding [Aa]id
- (3) Finding aid:
- (2) Online finding aid:
- (1) Free Access: Catalogue of CRCR Research Holdings (finding aid/box listing)
- (1) Finding aid, pt. [1-5,6-12,13-14,15-18,19,20,21,22] ** note there will be a lot of links on this page
- (1) [Place name, ex: Athabasca Landing] finding aid: ** note there will be a lot of links on this page

What I am planning on doing
- [ ] investigate why the button is created with javascript
- [ ] perhaps not do that
- [ ] investigate why links are coming from Symphony WS rather than Solr
- [ ] perhaps not do that
- [ ] add helper to deal with logic around the 'electronic_access' div

**Comment by seanluyk** [comment]
@pgwillia @weiweishi the question of why we grab 856 links (or pretty much anything other than item status) using WS is a big one that's come up recently, so it's good that you're looking at alternatives. Everytime there's a Symphony outage for reindexing, we lose all links to eBooks and the holdings table, which is not ideal IMHO. I'm in favour of indexing as much as possible and letting SOLR do its work, rather than relying on a limited/crappy API

**Comment by theLinkResolver** [comment]
I believe the benefit to pulling them out of WS is so URL fixes are live.

**Comment by seanluyk** [comment]
@theLinkResolver I figured as much but was also under the impression that these changes were done on a nightly job. Do you happen to know if there are a large number of changes made during the day as a regular practice or whether they would be exceptions?

**Comment by theLinkResolver** [comment]
@seanluyk For sure they are picked up overnight, but we do fix/edit lots of URLs all day - I'll draw in the ebookers for their take.

**Comment by seanluyk** [comment]
Thanks, @theLinkResolver!

**Comment by seanluyk** [comment]
Working in prod
