### ISSUE TITLE
New Books List

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#882]
ILS-team will produce list of catkeys and we can build in a static page.

**Comment by redlibrarian** [comment]
This is list is being sent to me by email right now. We need to a) implement and b) automate this process.

**Comment by redlibrarian** [comment]
I've built a proof of concept into the application, but we need to discuss how we want it to behave. I'll put it on the agenda for the next @ualbertalib/discovery-testing meeting (next Monday).

**Comment by theLinkResolver** [comment]
@redlibrarian I checked and there is a MARC field for Date/time stamp (005) but it won't help us with this. I think the data you need will have to come from the item record:

![datecreated](https://cloud.githubusercontent.com/assets/14913579/14438018/3a837a68-ffe1-11e5-9c26-e3abecf0c231.jpg)

Items added to existing records (vs. newly-created records) are important to include, because another NEOS library may have something before we do, and we want to report our acquisition when it happens. However, we don't want to see single issues of serials (and also likely not volumes of multi-part monos) showing up in the lists as was mentioned in our meeting. 

It's like you need to look at the item creation date for a UA item but then disqualify the title if there is already another UA item (BUT you don't want to exclude when two items were created on the same day, e.g. a two-volume monograph).

**Comment by redlibrarian** [comment]
All of a sudden the logic behind this has increased exponentially. Question for the @ualbertalib/discovery-testing - I've been assuming "new books" meant "new to UAL", but in a consortial environment, is this actually the case? People can request new books from anyway, so should the new book facet be built on "new to NEOS" logic instead?

**Comment by redlibrarian** [comment]
I think this is unlikely to be implement in Release 3.0.

**Comment by theLinkResolver** [comment]
I'd guess "new to UAL" is what people want.

**Comment by redlibrarian** [comment]
Yes, apparently WAT decided that - but I think I might not have been there.

After conferring with @sjshores , the new plan is this: I won't be able to get the new books facet going for the May launch (the logic is too complicated for a quick fix), so I'm going to implement a basic static new books list with Jim's data for now, and then I'll look at the facet version in the summer.

**Comment by redlibrarian** [comment]
The solution to the technical problem came to me on my walk home - capturing it here to implement tomorrow: an "fq" search won't work as it needs to be part of the solr parameters (as in the SFX, Database, and EBook controllers). Somehow I need to parse the list of catkeys into the appropriate fq string and pass it to solr_parameters on controller load. Since this isn't a *query*, the catkey load could happen on application start, or something like that.

**Comment by redlibrarian** [comment]
OK, this is done and will be in place in the next release. There's an upper limit to the number of results you can retrieve with this method (using a list of IDs), which is approximately 300 records. This will have to do for now, but we will likely have to figure out something else in the summer.

**Comment by redlibrarian** [comment]
To access the new books list, the URL will be e.g. https://search-test.library.ualberta.ca/new_books

**Comment by redlibrarian** [comment]
Hm. I just thought of another approach that might work...

**Comment by theLinkResolver** [comment]
@redlibrarian What is the status of this?

**Comment by redlibrarian** [comment]
I thought this was in place (though not dynamically updated), but I'm getting an error in prod. I'll look into it.

**Comment by redlibrarian** [comment]
I think this is mostly built. Done when:

- [ ] Error is fixed and page is visible
- [ ] Pipeline is built so that we can get new lists of catkeys from Symphony periodically

**Comment by seanluyk** [comment]
Here's a related ticket: https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=32595#122487

I'm wondering why we can't simply include the date created info in the Symphony extract, and then create a facet that limits to the x most recent dates (e.g. 6 months)

**Comment by theLinkResolver** [comment]
@theLinkResolver Tagging myself here as some thought will need to be given to how RCRF material works. It's all loaded into a shadowed location, which means none of it will appear in a new books list when it's "new", depending on the parameters of the new books list function. The same is also anticipated to be done for HSS music scores (loading into a shadowed location, due to binding requirements).

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
