### ISSUE TITLE
missing OUR (licensing) info

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#883]
The OUR info isn't displaying for the ProQuest links in the ejournal record's 'simulated Get It window' (@redlibrarian do you have another name for this?):

https://www.library.ualberta.ca/catalog/954925402586

normal get it window: http://bit.ly/1PFtie1

**Comment by theLinkResolver** [comment]
@redlibrarian gah, sorry, is this the same as #762?

**Comment by theLinkResolver** [comment]
@redlibrarian All the Proquest targets were just renamed with this week's update. Did you say that renaming targets could cause this?

**Comment by redlibrarian** [comment]
@theLinkResolver Yes, that's what's done it. I'll get an updated file from Ernie. It's not as simple as using the target name, unfortunately...

**Comment by theLinkResolver** [comment]
@redlibrarian Ugh. I'd say that target name changes occur quite regularly, which might not be what you'd previously heard... I guess, maybe they don't always affect us, but they do happen a lot.

**Comment by redlibrarian** [comment]
See #898 This is a process issue that we need to work out...

**Comment by redlibrarian** [comment]
I have a new file from Ernie I just need to implement it.

**Comment by redlibrarian** [comment]
OK. I've figured out a way that we don't need to rely on getting anything from Ernie. As long as the OUR links in SFX are kept up to date, Blacklight will be up to date. This will make for a much streamlined process. The patch will be in place in the next release.

**Comment by theLinkResolver** [comment]
@redlibrarian I don't see the OUR codes in search-test.

**Comment by redlibrarian** [comment]
I see them in production and on my workstation. I think this might be a peculiarity with the test environment.

**Comment by theLinkResolver** [comment]
@redlibrarian Still not seeing them..

**Comment by redlibrarian** [comment]
I don't know what's going on. I see them on my workstation, but not in test or production.

**Comment by redlibrarian** [comment]
I've asked our sysadmin if there's an issue with access on the test and production machines.

**Comment by redlibrarian** [comment]
Gah. I've figured out why this is happening. Months ago, we had the same problem (OUR appearing on my workstation, but not in test or prod). It turned out the security certificate was blocking "http://tal.scholarsportal.info" because it was insecure, while our test and prod instances are running on https. We fixed it by changing the scholarsportal link in our code to https.

But, a couple of weeks ago I changed the code to use the link that is in the SFX API response, so that we can get out of maintaining OUR links in the Blacklight codebase. This works *but* the link that is in SFX is... the insecure http link, so we are back to the problem of the OUR information being blocked when run over SSL.

Ideally, we could make a bulk change in SFX, but I don't think this is possible without going straight to the MySQL/MariaDB database. I'm going to see if I can hack in a fix in Blacklight...

**Comment by redlibrarian** [comment]
OK, I've managed to change the OUR link to https on the fly, so that should work. We'll check in the next release.

**Comment by redlibrarian** [comment]
I've pushed a fix - hopefully this will be fixed in test and prod today/tomorrow.

**Comment by redlibrarian** [comment]
@theLinkResolver I'm on wireless right now so I can't test this. Can you check in search-test and see if this is working - the new code was just pushed into test.

**Comment by theLinkResolver** [comment]
@redlibrarian It's working!!

**Comment by redlibrarian** [comment]
Excellent! It should work in prod once we push this code up.

**Comment by redlibrarian** [comment]
This is working.
