### ISSUE TITLE
User testing - next phase

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#907]
-- font
-- buttons/navigations
-- anything else

We should get together with Sonya to talk about next stage of user testing.

**Comment by theLinkResolver** [comment]
@gooyers @ualbertalib/discovery-testing Some other usability testing considerations?

Usefulness of call number filter - #892 
Subject search usability, perceived usefulness - #864 
Clarity around authorship - #827 
Expanding filter lists/the _More_ link - #563

**Comment by seanluyk** [comment]
One UX concern that I've been getting lots of feedback on is about how well users can distinguish between similar items from the various views. This is mostly a labeling/display issue, but IMO it plays a huge part in how users interact with the system. So a concrete example of a usability test for this particular issue would be to ask users what information they expect to see in different places (i.e. in bento, results, and record views), what's missing in what they're seeing now, etc.

**Comment by gooyers** [comment]
I'm finalizing some questions for a revised usability test that I will run by @redlibrarian and Sonya.

Subject headings, call numbers, interface (buttons, fonts) will all have specific questions devoted to them. 

The previous usability tests featured follow up questions in the results and item record views regarding 'what information do you think is missing?' and users usually respond positively and don't raise issues. 

But I do agree with @seanluyk that users aren't distinguishing between similar items in different views. The most obvious example being journal titles. Users are either slightly surprised to see journal results in the Books & more box (as Journals has its own box). Previously users were experiencing issues because they had to click into individual item records to tell the differences between items with the same title. This has been alleviated by the addition of author information (as well as format and year) to the bento box view.

**Comment by seanluyk** [comment]
Closing as this predates the completion of the Discovery Usability Report. Future user testing to come.
