### ISSUE TITLE
MEDLINE not being included in Blacklight search

### ISSUE THREAD

**Issue by lindaslater** [ualbertalib/discovery#909]
Try searching "cancer" and then look at the list of Content Providers.  MEDLINE is not among them.  However, in EDS, MEDLINE is at the top of the list when you search "cancer".    Is there anyway to fix this?

Also, how is Blacklight doing the relevancy ranking on the databases page?  If I search **medicine**,  the main file of MEDLINE is #52 on the list.  A MEDLINE subfile called MEDLINE In-Process & Other Non-Indexed Citations appears as #29, but most people would be interested in the full MEDLINE database (#52).  Likewise, if I search **nursing**, the major nursing database CINAHL is #14.   Is this related to the issue you spoke about in PSC, where too many subjects associations have been added to the Asset entry in LibGuides?

**Comment by redlibrarian** [comment]
Thanks @lindaslater . Because we have to maintain the list of databases in both EDS and the Blacklight instance of EDS separately and manually, MEDLINE wasn't enabled in the BL instance. I've enabled it now - it should be visible in BL within the hour.

The BL database search uses the same relevance algorithm as for other kinds of materials. So, the title is weighted highly, then the description. I'm not sure how the number of subjects is playing into the relevance in this case. I'll have to get back to you on that one.

**Comment by redlibrarian** [comment]
This is fixed now. A search for "medicine" lists MEDLINE first in the list of content providers.

Also, I checked the Solr configuration, and the way we're indexing databases right now, the subjects are ranked for databases the same as for other record types: so the more often a search term appears in the subject field (including all subjects in the record), the higher the weighting will be. So no, the number of subjects assigned to a database shouldn't affect the relevancy like that. Does that answer your questions, @lindaslater ?

**Comment by lindaslater** [comment]
Thanks, Sam,
That does answer my question, and just tested things, and MEDLINE results
are now included in the blacklight search.

Linda

*Linda Slater*, Public Services Manager, John W. Scott Health Sciences
Library, 2K312 WMC
University of Alberta, Edmonton, AB T6G 2R7.  Tel:  780-492-7948. Fax:
780-492-6960. Email:  linda.slater@ualberta.ca

**Comment by redlibrarian** [comment]
Great!
