### ISSUE TITLE
display summary of coverage for e-journals when holdings presented as SFX links

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#916]
A summary of our e-journal coverage is presented in the records that come from Symphony, as part of the "click here" link (e.g. 1869- in the following record):

https://www.library.ualberta.ca/catalog/6866795

@redlibrarian When we present the holdings as SFX links, could we provide a summary statement sources from the records or from the info @jhennig provides for SFX2Sirsi, under the title in a similar fashion? Currently, the user needs to check each line in the SFX link table to see if we hold the year s/he is looking for:

https://www.library.ualberta.ca/catalog/954925427238

**Comment by redlibrarian** [comment]
@theLinkResolver The thing is that a user is still going to have to check the SFX holdings table to click on the subscription they want/need, so I'm not sure adding the summary holdings info saves the user anything. This, to me, is different from the Symphony records because we have to privilege/present one link out of many, and because the list of holdings can potentially be huge. I don't think this is the case with SFX records (i.e. are there any SFX records with, say, 10 or more active targets?)

**Comment by theLinkResolver** [comment]
@redlibrarian They're out there...

Scientific American 12 links
Germanic Review 11 links
Canadian Journal of Sociology 11 links
Library Journal 17 links
School library journal 13 links
Journal of Education for Business 10 links

I was going to take a wait-and-see-for-user/public-services-feedback approach for this one but was strongly encouraged to submit the idea at this time.
