### ISSUE TITLE
General cleanup of ingest code

### ISSUE THREAD

**Issue by nmacgreg** [ualbertalib/discovery#920]
# Friendly to Monitoring
In the current code, the daily Symphony, database, and SFX ingests require a human in the loop, to read their log files and determine whether they were successful, or not.  As we don't have staff for this role, these jobs have failed frequently, but nobody is checking, so we're not aware of these failures.   Please modify these programs so their success or failure is clear, to reduce the operational cost of this service!  (First suggestion: clean up all the warning messages...)

To be clear, I need Nagios to be able to monitor whether each ingest in the last 24-hour period was successful or not.   Extending Nagios' envelope in this manner typically means I must write a new program, typically a shell/perl script, to determine status and provide results back to the Nagios server.   For instance, parsing the logfile output from the ingest jobs, is one possible approach, but in this instance, the log files are sprinkled with warning/error messages, sometimes contain lines from multiple different phases of the ingest process, contain a variable number of lines, and don't contain a clear, concise line indicating success or failure (eg, something I could grep).

For example, something that would be easy for Nagios monitor, would be to write a status file containing a one-line success-or-failure code/string.   The timestamp on the file would indicate to my plugin whether it ran at all, and the contents can be read to determine whether it worked, or not.   Also, rake makes these tasks seem similar: they're all executed in the same fashion.  Clearly, though, under the covers, they're using different codebases.  Despite that, for interface convenience, it would be nice if they all reported their success/failure in the same manner, allowing me to write one piece of plugin code with perhaps a variable filename, to check the status of each interface job.

# Robustness
- In the SFX ingest, for instance, there is a download phase which occasionally reports an error because it doesn't have permission to write to file sfx.xml.  Yet, after the download fails, the ingest process blithely proceeds to load data from the old sfx.xml  (and, incidiously, the log file indicates success, if you only read the last few lines).
- On multiple occasions, I've run a Symphony ingest in Production from the commandline, had it report a failure, and got my prompt back, _but later found a java process running in the background, somehow preventing any further ingests from occurring_!  That code needs better error handling to prevent this runaway scenario.  (While we're not running symphony ingests in Production at this time, we plan to, again, in the next few months.)
- Why does ingest.log grow to a small size, get rotated only once, and leave us with an incomplete record of transaction status?  Is this a "java thing"?  Can we fix it?  Do we need ingest.log at all?  Could you just turn it off & get better performance, since we're logging separately?

Overall, I get the feeling the ingest code is copied from elsewhere, poorly understood, and not of the enterprise quality that is required, given that we're relying on it to receive daily updates.  (Sorry for raining on your parade, don't mean to be negative.)

**Comment by redlibrarian** [comment]
Thanks @nmacgreg 

ingest.log was added in order to give clean logging for the ingest processes that I wrote (databases and - for the most part - SFX). When I run, for example, a database ingest, I get the following output:

[2016-03-07T11:18:31.793291 #13938]  INFO -- : --- Starting ingest on 2016-03-07 11:18:31 -0700 ---
[2016-03-07T11:18:31.793385 #13938]  INFO -- : Starting database ingest for databases
[2016-03-07T11:19:29.015226 #13938]  INFO -- : Solr commit response: Ingest succeeded. Elapsed time 2260 ms.
[2016-03-07T11:19:29.015311 #13938]  INFO -- : --- Finished ingest on 2016-03-07 11:19:29 -0700 ---

Is this not what you see? Would you like to see something else? This is all controllably, I just need to know what you want to see here. As for log rotation/truncation - I don't see that happening here, but I can look into that. 

However, it looks to me as if the logging of all solr ingests are configured in the logging.properties file for Solr. I assume this is or has been something that @henryzhang87  has been managing. Certainly for Symphony and SFX records, the logging isn't something needs "changing code" to fix. So, for friendless to logging, I think the first place to check is the configuration of logging within Solr. An example of the logging.properties for standalone/bundled solr can be found here: https://github.com/projectblacklight/blacklight-jetty/blob/master/etc/logging.properties

As for Robustness, as I say, if there's something going on with ingest.log I can look into that. I thought it was what you wanted in order to get the kind of logging information you're talking about. However, if you don't think it's necessary, all Solr ingests should be logged through Solr's logging module (i.e. not part of my Blacklight code). I can deal with the sfx.xml file issue. As for the runaway java process - I would need more information to work on that. Does it happen for any kind of failure?

Anyway, let me know whether you want me to stop using ingest.log. That's easy enough, as I added it to provide more logging info; though as I say, the Solr ingest log is the standard logging tool for Blacklight.
