### ISSUE TITLE
discrepancies when searching named collections

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#948]
I'm a bit concerned about these discrepancies, as noted by Special Collections staff:

"Priesterseminar library of the Archbishop of Salzburg"
iLink: 2,867 titles
[Blacklight](https://www.library.ualberta.ca/symphony?f[electronic_tesim][]=Online&q=%22Priesterseminar+library+of+the+Archbishop+of+Salzburg%22): 2,855 titles

"Dr. Ronald B. Madge Entomology Collection"
iLink: 873 titles
[BL](https://www.library.ualberta.ca/symphony?q=%22Dr.+Ronald+B.+Madge+Entomology+Collection%22): 827 titles

I'm hoping it may have something to do with how fresh the data in Blacklight is.

**Comment by redlibrarian** [comment]
The new index should be up in test today, let's check it then.

**Comment by redlibrarian** [comment]
A new full reindex is on search-test right now, and it's still showing the same difference in numbers. Is it possible that the iLink search is finding that text string in a field we aren't indexing (i.e. a field other than the 500$a)?

**Comment by theLinkResolver** [comment]
@redlibrarian Good question. But, I tried the same searches in iLink, this time limiting to the 590, and got the same number of results.

FYI, for testing, the iLink search string is e.g.: 'Dr. Ronald B. Madge Entomology Collection' {590}

**Comment by seanluyk** [comment]
Adding University of Alberta copy to the search string in BL yields results closer to iLink (at least for the first example), and with the second example the language in this note isn't 100% the same (e.g. some say "copy 2 in the Robert B. Made collection) so I think this issue is closable as it reflects how the relevancy ranking/thresholds work in BL/SOLR. I've added it to our list of problem queries for investigation nonetheless, as there could be some modifications to improve this
