### ISSUE TITLE
Context sensitive advanced search.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#954]

**Comment by theLinkResolver** [comment]
If we go this way, is it true that we would no longer have a place where advanced search results integrate all three of Symphony + Journals + Databases (plus future UA collections), since the advanced search would always be launched from within one of those groupings?

In case we don't want to take that possibility away completely, we could have a way of expanding like this:

- Books Media & More results chosen by the user
- User decides to click Advanced Search within Books Media & More
- Does a search
- Has the option to expand: "Add Journal & Database Titles to search?"

**Comment by seanluyk** [comment]
Closing as this is no longer relevant with the removal of bento view.
